#!/usr/bin/env node
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   codegen-engines.mjs                                :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: dlesieur <dlesieur@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/06/01 12:00:00 by dlesieur          #+#    #+#             */
/*   Updated: 2026/06/01 12:00:00 by dlesieur         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
//
// Regenerate `src/generated/engines.ts` from a live query-router.
//
// Usage:
//   node ./scripts/codegen-engines.mjs                 (default URL)
//   ENGINES_URL=http://localhost:18000/query/v1/engines node ./scripts/codegen-engines.mjs
//
// When OFFLINE / no live stack, the script exits 0 without touching the file —
// the checked-in baseline in src/generated/engines.ts is the source of truth.
//
// `--strict` mode fails if the live catalog has *drifted* from the checked-in
// baseline. CI uses this to ensure SDK types match what the server actually
// advertises.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SDK_ROOT = path.resolve(__dirname, '..');
const OUT_FILE = path.resolve(SDK_ROOT, 'src/generated/engines.ts');

const DEFAULT_URL = process.env.ENGINES_URL ?? 'http://localhost:18000/query/v1/engines';
const STRICT = process.argv.includes('--strict');

const HEADER = `/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   engines.ts                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: dlesieur <dlesieur@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/06/01 12:00:00 by dlesieur          #+#    #+#             */
/*   Updated: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} by dlesieur         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
//
// **Generated** engine catalog (M10) — regenerated by codegen-engines.mjs.
//
// To regenerate from a live stack:
//   node apps/baas/sdk/scripts/codegen-engines.mjs
//
// The shipped baseline matches the engines registered in
// apps/baas/mini-baas-infra/src/apps/query-router/src/query/query.service.ts.
`;

function renderCaps(details) {
  const entries = details.map((d) => {
    const c = d.capabilities;
    const semantic = c.semantic ?? fallbackSemantic(d.engine);
    return `  ${d.engine}: { read: ${c.read}, write: ${c.write}, upsert: ${c.upsert}, txIntra: ${c.txIntra}, stream: ${c.stream}, semantic: { joins: '${semantic.joins}', patternSearch: '${semantic.patternSearch}', ddl: ${semantic.ddl}, migrationVersioning: ${semantic.migrationVersioning}, latencyClass: '${semantic.latencyClass}' } },`;
  });
  return `export const ENGINE_CAPS = {
${entries.join('\n')}
} as const;`;
}

function fallbackSemantic(engine) {
  const defaults = {
    postgresql: { joins: 'native', patternSearch: 'native', ddl: true, migrationVersioning: true, latencyClass: 'native' },
    mongodb: { joins: 'limited', patternSearch: 'indexed', ddl: true, migrationVersioning: true, latencyClass: 'native' },
    mysql: { joins: 'native', patternSearch: 'native', ddl: true, migrationVersioning: true, latencyClass: 'native' },
  };
  return defaults[engine] ?? { joins: 'none', patternSearch: 'none', ddl: false, migrationVersioning: false, latencyClass: 'adapter' };
}

const TAIL = `

export type EngineId = keyof typeof ENGINE_CAPS;

export type EngineCaps<E extends EngineId = EngineId> = (typeof ENGINE_CAPS)[E];

export const ENGINE_IDS = Object.keys(ENGINE_CAPS) as EngineId[];

/** Engines that advertise \`stream: true\` (can be subscribed to). */
export type StreamableEngine = {
  [E in EngineId]: (typeof ENGINE_CAPS)[E]['stream'] extends true ? E : never;
}[EngineId];

/** Engines that advertise \`txIntra: true\` (support intra-engine transactions). */
export type TransactionalEngine = {
  [E in EngineId]: (typeof ENGINE_CAPS)[E]['txIntra'] extends true ? E : never;
}[EngineId];

/** Engines that advertise \`upsert: true\`. */
export type UpsertableEngine = {
  [E in EngineId]: (typeof ENGINE_CAPS)[E]['upsert'] extends true ? E : never;
}[EngineId];

/** Runtime introspection — keep this in lockstep with \`EnginesController\`. */
export interface EngineDescriptor {
  engine: EngineId;
  capabilities: EngineCaps;
}

export interface EnginesResponse {
  engines: EngineId[];
  details: EngineDescriptor[];
}
`;

async function fetchLive(url) {
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } catch (err) {
    return { error: err instanceof Error ? err.message : String(err) };
  }
}

// Strip control chars from values that originate in the live HTTP response
// before logging them, so a malicious server reply cannot forge log lines
// (jssecurity:S5145 — log injection).
function logSafe(value) {
  return String(value).replace(/[\u0000-\u001f\u007f]/g, ' ');
}

async function main() {
  const live = await fetchLive(DEFAULT_URL);
  if (live.error) {
    console.error(`[codegen-engines] could not reach ${DEFAULT_URL}: ${logSafe(live.error)}`);
    if (STRICT) {
      console.error('[codegen-engines] --strict mode requires a live stack');
      process.exit(2);
    }
    console.error('[codegen-engines] keeping baseline at src/generated/engines.ts (no-op)');
    return;
  }

  if (!Array.isArray(live.details) || live.details.length === 0) {
    console.error('[codegen-engines] live /engines response is malformed');
    process.exit(3);
  }

  const next = HEADER + '\n' + renderCaps(live.details) + TAIL;

  const current = await fs.readFile(OUT_FILE, 'utf8').catch(() => '');
  if (STRICT && current && current.trim() !== next.trim()) {
    console.error('[codegen-engines] --strict: drift detected between baseline and live catalog');
    process.exit(4);
  }

  await fs.writeFile(OUT_FILE, next);
  console.log(`[codegen-engines] wrote ${logSafe(live.details.length)} engines to ${path.relative(SDK_ROOT, OUT_FILE)}`);
}

try {
  await main();
} catch (err) {
  console.error('[codegen-engines] fatal:', err);
  process.exit(1);
}
