/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import grobase.models.Error

import com.squareup.moshi.Json

import grobase.infrastructure.ApiClient
import grobase.infrastructure.ApiResponse
import grobase.infrastructure.ClientException
import grobase.infrastructure.ClientError
import grobase.infrastructure.ServerException
import grobase.infrastructure.ServerError
import grobase.infrastructure.MultiValueMap
import grobase.infrastructure.PartConfig
import grobase.infrastructure.RequestConfig
import grobase.infrastructure.RequestMethod
import grobase.infrastructure.ResponseType
import grobase.infrastructure.Success
import grobase.infrastructure.toMultiValue

open class RestApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://127.0.0.1:8002")
        }
    }

    /**
     * DELETE /rest/v1/{resource}
     * Delete rows matching the filter.
     * 
     * @param resource Table or view name.
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun restDelete(resource: kotlin.String) : Unit {
        val localVarResponse = restDeleteWithHttpInfo(resource = resource)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /rest/v1/{resource}
     * Delete rows matching the filter.
     * 
     * @param resource Table or view name.
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun restDeleteWithHttpInfo(resource: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = restDeleteRequestConfig(resource = resource)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation restDelete
     *
     * @param resource Table or view name.
     * @return RequestConfig
     */
    fun restDeleteRequestConfig(resource: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/rest/v1/{resource}".replace("{"+"resource"+"}", encodeURIComponent(resource.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /rest/v1/{resource}
     * Insert one or many rows.
     * 
     * @param resource Table or view name.
     * @param requestBody 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun restInsert(resource: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : Unit {
        val localVarResponse = restInsertWithHttpInfo(resource = resource, requestBody = requestBody)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /rest/v1/{resource}
     * Insert one or many rows.
     * 
     * @param resource Table or view name.
     * @param requestBody 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun restInsertWithHttpInfo(resource: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : ApiResponse<Unit?> {
        val localVariableConfig = restInsertRequestConfig(resource = resource, requestBody = requestBody)

        return request<kotlin.collections.Map<kotlin.String, kotlin.Any>, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation restInsert
     *
     * @param resource Table or view name.
     * @param requestBody 
     * @return RequestConfig
     */
    fun restInsertRequestConfig(resource: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : RequestConfig<kotlin.collections.Map<kotlin.String, kotlin.Any>> {
        val localVariableBody = requestBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/rest/v1/{resource}".replace("{"+"resource"+"}", encodeURIComponent(resource.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /rest/v1/rpc/{fn}
     * Call a Postgres stored function (PostgREST RPC).
     * 
     * @param fn 
     * @param requestBody  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun restRpc(fn: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null) : Unit {
        val localVarResponse = restRpcWithHttpInfo(fn = fn, requestBody = requestBody)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /rest/v1/rpc/{fn}
     * Call a Postgres stored function (PostgREST RPC).
     * 
     * @param fn 
     * @param requestBody  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun restRpcWithHttpInfo(fn: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>?) : ApiResponse<Unit?> {
        val localVariableConfig = restRpcRequestConfig(fn = fn, requestBody = requestBody)

        return request<kotlin.collections.Map<kotlin.String, kotlin.Any>, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation restRpc
     *
     * @param fn 
     * @param requestBody  (optional)
     * @return RequestConfig
     */
    fun restRpcRequestConfig(fn: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>?) : RequestConfig<kotlin.collections.Map<kotlin.String, kotlin.Any>> {
        val localVariableBody = requestBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/rest/v1/rpc/{fn}".replace("{"+"fn"+"}", encodeURIComponent(fn.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /rest/v1/{resource}
     * Select rows (PostgREST filters via query params).
     * Filters are PostgREST &#x60;column&#x3D;op.value&#x60; query params (&#x60;eq&#x60;, &#x60;neq&#x60;, &#x60;gt&#x60;, &#x60;gte&#x60;, &#x60;lt&#x60;, &#x60;lte&#x60;, &#x60;like&#x60;, &#x60;ilike&#x60;, &#x60;is&#x60;, &#x60;in&#x60;), plus &#x60;select&#x60;, &#x60;order&#x60;, &#x60;limit&#x60;, &#x60;offset&#x60;, and &#x60;or&#x60;. Send &#x60;Accept: application/vnd.pgrst.object+json&#x60; for &#x60;.single()&#x60;.
     * @param resource Table or view name.
     * @param select  (optional)
     * @param order  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return kotlin.collections.List<kotlin.Any>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun restSelect(resource: kotlin.String, select: kotlin.String? = null, order: kotlin.String? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null) : kotlin.collections.List<kotlin.Any> {
        val localVarResponse = restSelectWithHttpInfo(resource = resource, select = select, order = order, limit = limit, offset = offset)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<kotlin.Any>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /rest/v1/{resource}
     * Select rows (PostgREST filters via query params).
     * Filters are PostgREST &#x60;column&#x3D;op.value&#x60; query params (&#x60;eq&#x60;, &#x60;neq&#x60;, &#x60;gt&#x60;, &#x60;gte&#x60;, &#x60;lt&#x60;, &#x60;lte&#x60;, &#x60;like&#x60;, &#x60;ilike&#x60;, &#x60;is&#x60;, &#x60;in&#x60;), plus &#x60;select&#x60;, &#x60;order&#x60;, &#x60;limit&#x60;, &#x60;offset&#x60;, and &#x60;or&#x60;. Send &#x60;Accept: application/vnd.pgrst.object+json&#x60; for &#x60;.single()&#x60;.
     * @param resource Table or view name.
     * @param select  (optional)
     * @param order  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return ApiResponse<kotlin.collections.List<kotlin.Any>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun restSelectWithHttpInfo(resource: kotlin.String, select: kotlin.String?, order: kotlin.String?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<kotlin.collections.List<kotlin.Any>?> {
        val localVariableConfig = restSelectRequestConfig(resource = resource, select = select, order = order, limit = limit, offset = offset)

        return request<Unit, kotlin.collections.List<kotlin.Any>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation restSelect
     *
     * @param resource Table or view name.
     * @param select  (optional)
     * @param order  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return RequestConfig
     */
    fun restSelectRequestConfig(resource: kotlin.String, select: kotlin.String?, order: kotlin.String?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (select != null) {
                    put("select", listOf(select.toString()))
                }
                if (order != null) {
                    put("order", listOf(order.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/rest/v1/{resource}".replace("{"+"resource"+"}", encodeURIComponent(resource.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /rest/v1/{resource}
     * Update rows matching the filter.
     * 
     * @param resource Table or view name.
     * @param requestBody 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun restUpdate(resource: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : Unit {
        val localVarResponse = restUpdateWithHttpInfo(resource = resource, requestBody = requestBody)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /rest/v1/{resource}
     * Update rows matching the filter.
     * 
     * @param resource Table or view name.
     * @param requestBody 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun restUpdateWithHttpInfo(resource: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : ApiResponse<Unit?> {
        val localVariableConfig = restUpdateRequestConfig(resource = resource, requestBody = requestBody)

        return request<kotlin.collections.Map<kotlin.String, kotlin.Any>, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation restUpdate
     *
     * @param resource Table or view name.
     * @param requestBody 
     * @return RequestConfig
     */
    fun restUpdateRequestConfig(resource: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : RequestConfig<kotlin.collections.Map<kotlin.String, kotlin.Any>> {
        val localVariableBody = requestBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/rest/v1/{resource}".replace("{"+"resource"+"}", encodeURIComponent(resource.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
