/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.MfaEnrollResponse
import grobase.models.MfaEnrollResponseTotp

class MfaEnrollResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MfaEnrollResponse
        //val modelInstance = MfaEnrollResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `friendlyName`
        should("test friendlyName") {
            // uncomment below to test the property
            //modelInstance.friendlyName shouldBe ("TODO")
        }

        // to test the property `totp`
        should("test totp") {
            // uncomment below to test the property
            //modelInstance.totp shouldBe ("TODO")
        }

    }
}
