/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.QueryRequest

class QueryRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryRequest
        //val modelInstance = QueryRequest()

        // to test the property `databaseId`
        should("test databaseId") {
            // uncomment below to test the property
            //modelInstance.databaseId shouldBe ("TODO")
        }

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `resource`
        should("test resource") {
            // uncomment below to test the property
            //modelInstance.resource shouldBe ("TODO")
        }

        // to test the property `payload`
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

    }
}
