/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.SignedUrl

class SignedUrlTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SignedUrl
        //val modelInstance = SignedUrl()

        // to test the property `signedUrl`
        should("test signedUrl") {
            // uncomment below to test the property
            //modelInstance.signedUrl shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `method`
        should("test method") {
            // uncomment below to test the property
            //modelInstance.method shouldBe ("TODO")
        }

        // to test the property `bucket`
        should("test bucket") {
            // uncomment below to test the property
            //modelInstance.bucket shouldBe ("TODO")
        }

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

    }
}
