/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.StorageList200Response
import grobase.models.StorageObject

class StorageList200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StorageList200Response
        //val modelInstance = StorageList200Response()

        // to test the property `objects`
        should("test objects") {
            // uncomment below to test the property
            //modelInstance.objects shouldBe ("TODO")
        }

    }
}
