//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthAPI {

    /**
     Begin a social/OIDC OAuth flow (302 to the provider).
     
     - parameter provider: (query)  
     - parameter redirectTo: (query)  (optional)
     - parameter scopes: (query)  (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authAuthorize(provider: String, redirectTo: String? = nil, scopes: String? = nil) async throws {
        return try await authAuthorizeWithRequestBuilder(provider: provider, redirectTo: redirectTo, scopes: scopes).execute().body
    }

    /**
     Begin a social/OIDC OAuth flow (302 to the provider).
     - GET /auth/v1/authorize
     - The SDK's `auth.signInWithOAuth()` builds this URL; the browser is redirected here, gotrue 302s to the provider, then back to `redirect_to`.
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter provider: (query)  
     - parameter redirectTo: (query)  (optional)
     - parameter scopes: (query)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func authAuthorizeWithRequestBuilder(provider: String, redirectTo: String? = nil, scopes: String? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/auth/v1/authorize"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "provider": (wrappedValue: provider.encodeToJSON(), isExplode: true),
            "redirect_to": (wrappedValue: redirectTo?.encodeToJSON(), isExplode: true),
            "scopes": (wrappedValue: scopes?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get the authenticated user.
     
     - returns: User
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authGetUser() async throws -> User {
        return try await authGetUserWithRequestBuilder().execute().body
    }

    /**
     Get the authenticated user.
     - GET /auth/v1/user
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<User> 
     */
    open class func authGetUserWithRequestBuilder() -> RequestBuilder<User> {
        let localVariablePath = "/auth/v1/user"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<User>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Revoke the current session.
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authLogout() async throws {
        return try await authLogoutWithRequestBuilder().execute().body
    }

    /**
     Revoke the current session.
     - POST /auth/v1/logout
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<Void> 
     */
    open class func authLogoutWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/auth/v1/logout"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send a password-recovery email.
     
     - parameter authRecoverRequest: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authRecover(authRecoverRequest: AuthRecoverRequest) async throws {
        return try await authRecoverWithRequestBuilder(authRecoverRequest: authRecoverRequest).execute().body
    }

    /**
     Send a password-recovery email.
     - POST /auth/v1/recover
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter authRecoverRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func authRecoverWithRequestBuilder(authRecoverRequest: AuthRecoverRequest) -> RequestBuilder<Void> {
        let localVariablePath = "/auth/v1/recover"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: authRecoverRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Register a new user (email + password).
     
     - parameter signUpRequest: (body)  
     - returns: AuthSignUp200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authSignUp(signUpRequest: SignUpRequest) async throws -> AuthSignUp200Response {
        return try await authSignUpWithRequestBuilder(signUpRequest: signUpRequest).execute().body
    }

    /**
     Register a new user (email + password).
     - POST /auth/v1/signup
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter signUpRequest: (body)  
     - returns: RequestBuilder<AuthSignUp200Response> 
     */
    open class func authSignUpWithRequestBuilder(signUpRequest: SignUpRequest) -> RequestBuilder<AuthSignUp200Response> {
        let localVariablePath = "/auth/v1/signup"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: signUpRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AuthSignUp200Response>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter grantType
     */
    public enum GrantType_authToken: String, CaseIterable {
        case password = "password"
        case refreshToken = "refresh_token"
    }

    /**
     Exchange credentials for a session (password or refresh_token grant).
     
     - parameter grantType: (query)  
     - parameter tokenRequest: (body)  
     - returns: Session
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authToken(grantType: GrantType_authToken, tokenRequest: TokenRequest) async throws -> Session {
        return try await authTokenWithRequestBuilder(grantType: grantType, tokenRequest: tokenRequest).execute().body
    }

    /**
     Exchange credentials for a session (password or refresh_token grant).
     - POST /auth/v1/token
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter grantType: (query)  
     - parameter tokenRequest: (body)  
     - returns: RequestBuilder<Session> 
     */
    open class func authTokenWithRequestBuilder(grantType: GrantType_authToken, tokenRequest: TokenRequest) -> RequestBuilder<Session> {
        let localVariablePath = "/auth/v1/token"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: tokenRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "grant_type": (wrappedValue: grantType.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Session>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update the authenticated user (email / password / metadata).
     
     - parameter updateUserRequest: (body)  
     - returns: User
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authUpdateUser(updateUserRequest: UpdateUserRequest) async throws -> User {
        return try await authUpdateUserWithRequestBuilder(updateUserRequest: updateUserRequest).execute().body
    }

    /**
     Update the authenticated user (email / password / metadata).
     - POST /auth/v1/user
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter updateUserRequest: (body)  
     - returns: RequestBuilder<User> 
     */
    open class func authUpdateUserWithRequestBuilder(updateUserRequest: UpdateUserRequest) -> RequestBuilder<User> {
        let localVariablePath = "/auth/v1/user"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateUserRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<User>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Verify a signup/recovery/magiclink token.
     
     - parameter verifyRequest: (body)  
     - returns: AuthSignUp200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authVerify(verifyRequest: VerifyRequest) async throws -> AuthSignUp200Response {
        return try await authVerifyWithRequestBuilder(verifyRequest: verifyRequest).execute().body
    }

    /**
     Verify a signup/recovery/magiclink token.
     - POST /auth/v1/verify
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter verifyRequest: (body)  
     - returns: RequestBuilder<AuthSignUp200Response> 
     */
    open class func authVerifyWithRequestBuilder(verifyRequest: VerifyRequest) -> RequestBuilder<AuthSignUp200Response> {
        let localVariablePath = "/auth/v1/verify"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AuthSignUp200Response>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Open a verification challenge for an enrolled factor.
     
     - parameter factorId: (path)  
     - returns: MfaChallengeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mfaChallenge(factorId: String) async throws -> MfaChallengeResponse {
        return try await mfaChallengeWithRequestBuilder(factorId: factorId).execute().body
    }

    /**
     Open a verification challenge for an enrolled factor.
     - POST /auth/v1/factors/{factorId}/challenge
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter factorId: (path)  
     - returns: RequestBuilder<MfaChallengeResponse> 
     */
    open class func mfaChallengeWithRequestBuilder(factorId: String) -> RequestBuilder<MfaChallengeResponse> {
        var localVariablePath = "/auth/v1/factors/{factorId}/challenge"
        let factorIdPreEscape = "\(APIHelper.mapValueToPathItem(factorId))"
        let factorIdPostEscape = factorIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{factorId}", with: factorIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MfaChallengeResponse>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Enroll an MFA factor (TOTP or phone).
     
     - parameter mfaEnrollRequest: (body)  
     - returns: MfaEnrollResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mfaEnroll(mfaEnrollRequest: MfaEnrollRequest) async throws -> MfaEnrollResponse {
        return try await mfaEnrollWithRequestBuilder(mfaEnrollRequest: mfaEnrollRequest).execute().body
    }

    /**
     Enroll an MFA factor (TOTP or phone).
     - POST /auth/v1/factors
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter mfaEnrollRequest: (body)  
     - returns: RequestBuilder<MfaEnrollResponse> 
     */
    open class func mfaEnrollWithRequestBuilder(mfaEnrollRequest: MfaEnrollRequest) -> RequestBuilder<MfaEnrollResponse> {
        let localVariablePath = "/auth/v1/factors"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: mfaEnrollRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MfaEnrollResponse>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Remove an MFA factor.
     
     - parameter factorId: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mfaUnenroll(factorId: String) async throws {
        return try await mfaUnenrollWithRequestBuilder(factorId: factorId).execute().body
    }

    /**
     Remove an MFA factor.
     - DELETE /auth/v1/factors/{factorId}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter factorId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func mfaUnenrollWithRequestBuilder(factorId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/auth/v1/factors/{factorId}"
        let factorIdPreEscape = "\(APIHelper.mapValueToPathItem(factorId))"
        let factorIdPostEscape = factorIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{factorId}", with: factorIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Verify a challenge with a code; on success upgrades the session AAL.
     
     - parameter factorId: (path)  
     - parameter mfaVerifyRequest: (body)  
     - returns: Session
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func mfaVerify(factorId: String, mfaVerifyRequest: MfaVerifyRequest) async throws -> Session {
        return try await mfaVerifyWithRequestBuilder(factorId: factorId, mfaVerifyRequest: mfaVerifyRequest).execute().body
    }

    /**
     Verify a challenge with a code; on success upgrades the session AAL.
     - POST /auth/v1/factors/{factorId}/verify
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter factorId: (path)  
     - parameter mfaVerifyRequest: (body)  
     - returns: RequestBuilder<Session> 
     */
    open class func mfaVerifyWithRequestBuilder(factorId: String, mfaVerifyRequest: MfaVerifyRequest) -> RequestBuilder<Session> {
        var localVariablePath = "/auth/v1/factors/{factorId}/verify"
        let factorIdPreEscape = "\(APIHelper.mapValueToPathItem(factorId))"
        let factorIdPostEscape = factorIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{factorId}", with: factorIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: mfaVerifyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Session>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
