//
// QueryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class QueryAPI {

    /**
     List registered engines + capabilities.
     
     - returns: QueryEngines200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func queryEngines() async throws -> QueryEngines200Response {
        return try await queryEnginesWithRequestBuilder().execute().body
    }

    /**
     List registered engines + capabilities.
     - GET /query/v1/engines
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<QueryEngines200Response> 
     */
    open class func queryEnginesWithRequestBuilder() -> RequestBuilder<QueryEngines200Response> {
        let localVariablePath = "/query/v1/engines"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QueryEngines200Response>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Run one engine-agnostic data operation against a mount.
     
     - parameter queryRequest: (body)  
     - returns: QueryResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func queryExecute(queryRequest: QueryRequest) async throws -> QueryResponse {
        return try await queryExecuteWithRequestBuilder(queryRequest: queryRequest).execute().body
    }

    /**
     Run one engine-agnostic data operation against a mount.
     - POST /query/v1/execute
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter queryRequest: (body)  
     - returns: RequestBuilder<QueryResponse> 
     */
    open class func queryExecuteWithRequestBuilder(queryRequest: QueryRequest) -> RequestBuilder<QueryResponse> {
        let localVariablePath = "/query/v1/execute"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: queryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QueryResponse>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Introspect a mount's tables + live engine capabilities.
     
     - parameter dbId: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func querySchema(dbId: String) async throws -> [String: AnyCodable] {
        return try await querySchemaWithRequestBuilder(dbId: dbId).execute().body
    }

    /**
     Introspect a mount's tables + live engine capabilities.
     - GET /query/v1/{dbId}/schema
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter dbId: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func querySchemaWithRequestBuilder(dbId: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/query/v1/{dbId}/schema"
        let dbIdPreEscape = "\(APIHelper.mapValueToPathItem(dbId))"
        let dbIdPostEscape = dbIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{dbId}", with: dbIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Apply ONE schema-DDL operation to a mount.
     
     - parameter dbId: (path)  
     - parameter requestBody: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func querySchemaDdl(dbId: String, requestBody: [String: AnyCodable]) async throws {
        return try await querySchemaDdlWithRequestBuilder(dbId: dbId, requestBody: requestBody).execute().body
    }

    /**
     Apply ONE schema-DDL operation to a mount.
     - POST /query/v1/{dbId}/schema/ddl
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter dbId: (path)  
     - parameter requestBody: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func querySchemaDdlWithRequestBuilder(dbId: String, requestBody: [String: AnyCodable]) -> RequestBuilder<Void> {
        var localVariablePath = "/query/v1/{dbId}/schema/ddl"
        let dbIdPreEscape = "\(APIHelper.mapValueToPathItem(dbId))"
        let dbIdPostEscape = dbIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{dbId}", with: dbIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Single-mount atomic write batch (all-or-nothing).
     
     - parameter txnRequest: (body)  
     - returns: TxnResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func queryTxn(txnRequest: TxnRequest) async throws -> TxnResponse {
        return try await queryTxnWithRequestBuilder(txnRequest: txnRequest).execute().body
    }

    /**
     Single-mount atomic write batch (all-or-nothing).
     - POST /query/v1/txn
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter txnRequest: (body)  
     - returns: RequestBuilder<TxnResponse> 
     */
    open class func queryTxnWithRequestBuilder(txnRequest: TxnRequest) -> RequestBuilder<TxnResponse> {
        let localVariablePath = "/query/v1/txn"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TxnResponse>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
