//
// RestAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RestAPI {

    /**
     Delete rows matching the filter.
     
     - parameter resource: (path) Table or view name. 
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func restDelete(resource: String) async throws {
        return try await restDeleteWithRequestBuilder(resource: resource).execute().body
    }

    /**
     Delete rows matching the filter.
     - DELETE /rest/v1/{resource}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter resource: (path) Table or view name. 
     - returns: RequestBuilder<Void> 
     */
    open class func restDeleteWithRequestBuilder(resource: String) -> RequestBuilder<Void> {
        var localVariablePath = "/rest/v1/{resource}"
        let resourcePreEscape = "\(APIHelper.mapValueToPathItem(resource))"
        let resourcePostEscape = resourcePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resource}", with: resourcePostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Insert one or many rows.
     
     - parameter resource: (path) Table or view name. 
     - parameter requestBody: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func restInsert(resource: String, requestBody: [String: AnyCodable]) async throws {
        return try await restInsertWithRequestBuilder(resource: resource, requestBody: requestBody).execute().body
    }

    /**
     Insert one or many rows.
     - POST /rest/v1/{resource}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter resource: (path) Table or view name. 
     - parameter requestBody: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func restInsertWithRequestBuilder(resource: String, requestBody: [String: AnyCodable]) -> RequestBuilder<Void> {
        var localVariablePath = "/rest/v1/{resource}"
        let resourcePreEscape = "\(APIHelper.mapValueToPathItem(resource))"
        let resourcePostEscape = resourcePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resource}", with: resourcePostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Call a Postgres stored function (PostgREST RPC).
     
     - parameter fn: (path)  
     - parameter requestBody: (body)  (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func restRpc(fn: String, requestBody: [String: AnyCodable]? = nil) async throws {
        return try await restRpcWithRequestBuilder(fn: fn, requestBody: requestBody).execute().body
    }

    /**
     Call a Postgres stored function (PostgREST RPC).
     - POST /rest/v1/rpc/{fn}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter fn: (path)  
     - parameter requestBody: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func restRpcWithRequestBuilder(fn: String, requestBody: [String: AnyCodable]? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/rest/v1/rpc/{fn}"
        let fnPreEscape = "\(APIHelper.mapValueToPathItem(fn))"
        let fnPostEscape = fnPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fn}", with: fnPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Select rows (PostgREST filters via query params).
     
     - parameter resource: (path) Table or view name. 
     - parameter select: (query)  (optional)
     - parameter order: (query)  (optional)
     - parameter limit: (query)  (optional)
     - parameter offset: (query)  (optional)
     - returns: [AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func restSelect(resource: String, select: String? = nil, order: String? = nil, limit: Int? = nil, offset: Int? = nil) async throws -> [AnyCodable] {
        return try await restSelectWithRequestBuilder(resource: resource, select: select, order: order, limit: limit, offset: offset).execute().body
    }

    /**
     Select rows (PostgREST filters via query params).
     - GET /rest/v1/{resource}
     - Filters are PostgREST `column=op.value` query params (`eq`, `neq`, `gt`, `gte`, `lt`, `lte`, `like`, `ilike`, `is`, `in`), plus `select`, `order`, `limit`, `offset`, and `or`. Send `Accept: application/vnd.pgrst.object+json` for `.single()`.
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter resource: (path) Table or view name. 
     - parameter select: (query)  (optional)
     - parameter order: (query)  (optional)
     - parameter limit: (query)  (optional)
     - parameter offset: (query)  (optional)
     - returns: RequestBuilder<[AnyCodable]> 
     */
    open class func restSelectWithRequestBuilder(resource: String, select: String? = nil, order: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<[AnyCodable]> {
        var localVariablePath = "/rest/v1/{resource}"
        let resourcePreEscape = "\(APIHelper.mapValueToPathItem(resource))"
        let resourcePostEscape = resourcePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resource}", with: resourcePostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "select": (wrappedValue: select?.encodeToJSON(), isExplode: true),
            "order": (wrappedValue: order?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AnyCodable]>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update rows matching the filter.
     
     - parameter resource: (path) Table or view name. 
     - parameter requestBody: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func restUpdate(resource: String, requestBody: [String: AnyCodable]) async throws {
        return try await restUpdateWithRequestBuilder(resource: resource, requestBody: requestBody).execute().body
    }

    /**
     Update rows matching the filter.
     - PATCH /rest/v1/{resource}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter resource: (path) Table or view name. 
     - parameter requestBody: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func restUpdateWithRequestBuilder(resource: String, requestBody: [String: AnyCodable]) -> RequestBuilder<Void> {
        var localVariablePath = "/rest/v1/{resource}"
        let resourcePreEscape = "\(APIHelper.mapValueToPathItem(resource))"
        let resourcePostEscape = resourcePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resource}", with: resourcePostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
