//
// StorageAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class StorageAPI {

    /**
     Create a bucket.
     
     - parameter name: (path)  
     - returns: StorageCreateBucket200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func storageCreateBucket(name: String) async throws -> StorageCreateBucket200Response {
        return try await storageCreateBucketWithRequestBuilder(name: name).execute().body
    }

    /**
     Create a bucket.
     - POST /storage/v1/bucket/{name}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter name: (path)  
     - returns: RequestBuilder<StorageCreateBucket200Response> 
     */
    open class func storageCreateBucketWithRequestBuilder(name: String) -> RequestBuilder<StorageCreateBucket200Response> {
        var localVariablePath = "/storage/v1/bucket/{name}"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StorageCreateBucket200Response>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete an object.
     
     - parameter bucket: (path)  
     - parameter key: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func storageDelete(bucket: String, key: String) async throws {
        return try await storageDeleteWithRequestBuilder(bucket: bucket, key: key).execute().body
    }

    /**
     Delete an object.
     - DELETE /storage/v1/object/{bucket}/{key}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter key: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func storageDeleteWithRequestBuilder(bucket: String, key: String) -> RequestBuilder<Void> {
        var localVariablePath = "/storage/v1/object/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = GrobaseAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Download object bytes (owner-scoped).
     
     - parameter bucket: (path)  
     - parameter key: (path)  
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func storageDownload(bucket: String, key: String) async throws -> URL {
        return try await storageDownloadWithRequestBuilder(bucket: bucket, key: key).execute().body
    }

    /**
     Download object bytes (owner-scoped).
     - GET /storage/v1/object/{bucket}/{key}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter key: (path)  
     - returns: RequestBuilder<URL> 
     */
    open class func storageDownloadWithRequestBuilder(bucket: String, key: String) -> RequestBuilder<URL> {
        var localVariablePath = "/storage/v1/object/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List objects under a prefix (owner-scoped).
     
     - parameter bucket: (path)  
     - parameter _prefix: (query)  (optional)
     - returns: StorageList200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func storageList(bucket: String, _prefix: String? = nil) async throws -> StorageList200Response {
        return try await storageListWithRequestBuilder(bucket: bucket, _prefix: _prefix).execute().body
    }

    /**
     List objects under a prefix (owner-scoped).
     - GET /storage/v1/list/{bucket}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter _prefix: (query)  (optional)
     - returns: RequestBuilder<StorageList200Response> 
     */
    open class func storageListWithRequestBuilder(bucket: String, _prefix: String? = nil) -> RequestBuilder<StorageList200Response> {
        var localVariablePath = "/storage/v1/list/{bucket}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "prefix": (wrappedValue: _prefix?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StorageList200Response>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List buckets.
     
     - returns: StorageListBuckets200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func storageListBuckets() async throws -> StorageListBuckets200Response {
        return try await storageListBucketsWithRequestBuilder().execute().body
    }

    /**
     List buckets.
     - GET /storage/v1/bucket
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<StorageListBuckets200Response> 
     */
    open class func storageListBucketsWithRequestBuilder() -> RequestBuilder<StorageListBuckets200Response> {
        let localVariablePath = "/storage/v1/bucket"
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StorageListBuckets200Response>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create a presigned URL (PUT or GET, TTL-clamped).
     
     - parameter bucket: (path)  
     - parameter key: (path)  
     - parameter storageSignRequest: (body)  (optional)
     - returns: SignedUrl
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func storageSign(bucket: String, key: String, storageSignRequest: StorageSignRequest? = nil) async throws -> SignedUrl {
        return try await storageSignWithRequestBuilder(bucket: bucket, key: key, storageSignRequest: storageSignRequest).execute().body
    }

    /**
     Create a presigned URL (PUT or GET, TTL-clamped).
     - POST /storage/v1/sign/{bucket}/{key}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter key: (path)  
     - parameter storageSignRequest: (body)  (optional)
     - returns: RequestBuilder<SignedUrl> 
     */
    open class func storageSignWithRequestBuilder(bucket: String, key: String, storageSignRequest: StorageSignRequest? = nil) -> RequestBuilder<SignedUrl> {
        var localVariablePath = "/storage/v1/sign/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: storageSignRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SignedUrl>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upload (owner-prefixed) — body is the raw object bytes.
     
     - parameter bucket: (path)  
     - parameter key: (path)  
     - parameter body: (body)  
     - returns: UploadResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func storageUpload(bucket: String, key: String, body: URL) async throws -> UploadResult {
        return try await storageUploadWithRequestBuilder(bucket: bucket, key: key, body: body).execute().body
    }

    /**
     Upload (owner-prefixed) — body is the raw object bytes.
     - PUT /storage/v1/object/{bucket}/{key}
     - API Key:
       - type: apiKey apikey (HEADER)
       - name: apiKey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bucket: (path)  
     - parameter key: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<UploadResult> 
     */
    open class func storageUploadWithRequestBuilder(bucket: String, key: String, body: URL) -> RequestBuilder<UploadResult> {
        var localVariablePath = "/storage/v1/object/{bucket}/{key}"
        let bucketPreEscape = "\(APIHelper.mapValueToPathItem(bucket))"
        let bucketPostEscape = bucketPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bucket}", with: bucketPostEscape, options: .literal, range: nil)
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = GrobaseAPI.basePath + localVariablePath
        let localVariableParameters = ["body": body]

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/octet-stream",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UploadResult>.Type = GrobaseAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
