//
// MfaEnrollRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MfaEnrollRequest: Codable, JSONEncodable, Hashable {

    public enum FactorType: String, Codable, CaseIterable {
        case totp = "totp"
        case phone = "phone"
    }
    public var factorType: FactorType? = .totp
    public var friendlyName: String?
    public var issuer: String?
    public var phone: String?

    public init(factorType: FactorType? = .totp, friendlyName: String? = nil, issuer: String? = nil, phone: String? = nil) {
        self.factorType = factorType
        self.friendlyName = friendlyName
        self.issuer = issuer
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case factorType = "factor_type"
        case friendlyName = "friendly_name"
        case issuer
        case phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(factorType, forKey: .factorType)
        try container.encodeIfPresent(friendlyName, forKey: .friendlyName)
        try container.encodeIfPresent(issuer, forKey: .issuer)
        try container.encodeIfPresent(phone, forKey: .phone)
    }
}

