//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelError: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var error: String?
    public var status: Int?

    public init(message: String? = nil, error: String? = nil, status: Int? = nil) {
        self.message = message
        self.error = error
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case error
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

