//
// QueryEngines200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QueryEngines200Response: Codable, JSONEncodable, Hashable {

    public var engines: [String]?

    public init(engines: [String]? = nil) {
        self.engines = engines
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case engines
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(engines, forKey: .engines)
    }
}

