//
// QueryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QueryRequest: Codable, JSONEncodable, Hashable {

    public var databaseId: String
    public var action: String
    public var resource: String
    public var payload: [String: AnyCodable]?

    public init(databaseId: String, action: String, resource: String, payload: [String: AnyCodable]? = nil) {
        self.databaseId = databaseId
        self.action = action
        self.resource = resource
        self.payload = payload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case databaseId = "database_id"
        case action
        case resource
        case payload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(databaseId, forKey: .databaseId)
        try container.encode(action, forKey: .action)
        try container.encode(resource, forKey: .resource)
        try container.encodeIfPresent(payload, forKey: .payload)
    }
}

