//
// SignUpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignUpRequest: Codable, JSONEncodable, Hashable {

    public var email: String
    public var password: String
    public var data: [String: AnyCodable]?

    public init(email: String, password: String, data: [String: AnyCodable]? = nil) {
        self.email = email
        self.password = password
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

