//
// StorageSignRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StorageSignRequest: Codable, JSONEncodable, Hashable {

    public enum Method: String, Codable, CaseIterable {
        case _get = "GET"
        case put = "PUT"
    }
    public var method: Method?
    public var expiresIn: Int?
    public var contentType: String?

    public init(method: Method? = nil, expiresIn: Int? = nil, contentType: String? = nil) {
        self.method = method
        self.expiresIn = expiresIn
        self.contentType = contentType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case method
        case expiresIn
        case contentType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
        try container.encodeIfPresent(contentType, forKey: .contentType)
    }
}

