//
// TxnResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TxnResponse: Codable, JSONEncodable, Hashable {

    public enum Guarantee: String, Codable, CaseIterable {
        case atomic = "atomic"
    }
    public var guarantee: Guarantee?
    public var mount: String?
    public var results: [TxnResponseResultsInner]?

    public init(guarantee: Guarantee? = nil, mount: String? = nil, results: [TxnResponseResultsInner]? = nil) {
        self.guarantee = guarantee
        self.mount = mount
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guarantee
        case mount
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(guarantee, forKey: .guarantee)
        try container.encodeIfPresent(mount, forKey: .mount)
        try container.encodeIfPresent(results, forKey: .results)
    }
}

