//
// UploadResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UploadResult: Codable, JSONEncodable, Hashable {

    public var bucket: String?
    public var key: String?
    public var size: Int?

    public init(bucket: String? = nil, key: String? = nil, size: Int? = nil) {
        self.bucket = bucket
        self.key = key
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bucket
        case key
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bucket, forKey: .bucket)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(size, forKey: .size)
    }
}

