//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct User: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var email: String?
    public var role: String?
    public var aud: String?
    public var appMetadata: [String: AnyCodable]?
    public var userMetadata: [String: AnyCodable]?
    public var createdAt: Date?

    public init(id: UUID, email: String? = nil, role: String? = nil, aud: String? = nil, appMetadata: [String: AnyCodable]? = nil, userMetadata: [String: AnyCodable]? = nil, createdAt: Date? = nil) {
        self.id = id
        self.email = email
        self.role = role
        self.aud = aud
        self.appMetadata = appMetadata
        self.userMetadata = userMetadata
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case role
        case aud
        case appMetadata = "app_metadata"
        case userMetadata = "user_metadata"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(aud, forKey: .aud)
        try container.encodeIfPresent(appMetadata, forKey: .appMetadata)
        try container.encodeIfPresent(userMetadata, forKey: .userMetadata)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension User: Identifiable {}
