# coding: utf-8

"""
    Grobase Public API

    Hand-authored, codegen-ready spec for the five public surfaces a client SDK consumes, at the exact Kong-routed paths the `@mini-baas/js` SDK targets (`/auth/v1`, `/rest/v1`, `/storage/v1`, `/query/v1`, `/functions/v1`).  This is the canonical spec for **A4 multi-language SDK codegen** (Python, Dart). It is deliberately separate from the per-service `*.json` documents collected by `openapi-collect.sh`, which describe each NestJS service at its *internal* port/path (not the public Kong prefix). Where a route is gotrue/PostgREST/Deno (not NestJS), only this hand-authored spec describes it — those services emit no `/docs-json`.  Verified against `sdk/src/core/routes.ts` (the SDK's route table) and the live stack on 2026-06-13.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grobase.models.auth_sign_up200_response import AuthSignUp200Response

class TestAuthSignUp200Response(unittest.TestCase):
    """AuthSignUp200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthSignUp200Response:
        """Test AuthSignUp200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthSignUp200Response`
        """
        model = AuthSignUp200Response()
        if include_optional:
            return AuthSignUp200Response(
                access_token = '',
                token_type = '',
                expires_in = 56,
                expires_at = 56,
                refresh_token = '',
                user = grobase.models.user.User(
                    id = '', 
                    email = '', 
                    role = '', 
                    aud = '', 
                    app_metadata = { }, 
                    user_metadata = { }, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                id = '',
                email = '',
                role = '',
                aud = '',
                app_metadata = { },
                user_metadata = { },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AuthSignUp200Response(
                access_token = '',
                id = '',
        )
        """

    def testAuthSignUp200Response(self):
        """Test AuthSignUp200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
