/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.apis.QueryApi
import grobase.models.Error
import grobase.models.QueryEngines200Response
import grobase.models.QueryRequest
import grobase.models.QueryResponse
import grobase.models.TxnRequest
import grobase.models.TxnResponse

class QueryApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryApi
        //val apiInstance = QueryApi()

        // to test queryEngines
        should("test queryEngines") {
            // uncomment below to test queryEngines
            //val result : QueryEngines200Response = apiInstance.queryEngines()
            //result shouldBe ("TODO")
        }

        // to test queryExecute
        should("test queryExecute") {
            // uncomment below to test queryExecute
            //val queryRequest : QueryRequest =  // QueryRequest | 
            //val result : QueryResponse = apiInstance.queryExecute(queryRequest)
            //result shouldBe ("TODO")
        }

        // to test querySchema
        should("test querySchema") {
            // uncomment below to test querySchema
            //val dbId : kotlin.String = dbId_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.querySchema(dbId)
            //result shouldBe ("TODO")
        }

        // to test querySchemaDdl
        should("test querySchemaDdl") {
            // uncomment below to test querySchemaDdl
            //val dbId : kotlin.String = dbId_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //apiInstance.querySchemaDdl(dbId, requestBody)
        }

        // to test queryTxn
        should("test queryTxn") {
            // uncomment below to test queryTxn
            //val txnRequest : TxnRequest =  // TxnRequest | 
            //val result : TxnResponse = apiInstance.queryTxn(txnRequest)
            //result shouldBe ("TODO")
        }

    }
}
