/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.apis.RestApi
import grobase.models.Error

class RestApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestApi
        //val apiInstance = RestApi()

        // to test restDelete
        should("test restDelete") {
            // uncomment below to test restDelete
            //val resource : kotlin.String = resource_example // kotlin.String | Table or view name.
            //apiInstance.restDelete(resource)
        }

        // to test restInsert
        should("test restInsert") {
            // uncomment below to test restInsert
            //val resource : kotlin.String = resource_example // kotlin.String | Table or view name.
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //apiInstance.restInsert(resource, requestBody)
        }

        // to test restRpc
        should("test restRpc") {
            // uncomment below to test restRpc
            //val fn : kotlin.String = fn_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //apiInstance.restRpc(fn, requestBody)
        }

        // to test restSelect
        should("test restSelect") {
            // uncomment below to test restSelect
            //val resource : kotlin.String = resource_example // kotlin.String | Table or view name.
            //val select : kotlin.String = select_example // kotlin.String | 
            //val order : kotlin.String = order_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.restSelect(resource, select, order, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test restUpdate
        should("test restUpdate") {
            // uncomment below to test restUpdate
            //val resource : kotlin.String = resource_example // kotlin.String | Table or view name.
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //apiInstance.restUpdate(resource, requestBody)
        }

    }
}
