/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.apis.StorageApi
import grobase.models.Error
import grobase.models.SignedUrl
import grobase.models.StorageCreateBucket200Response
import grobase.models.StorageList200Response
import grobase.models.StorageListBuckets200Response
import grobase.models.StorageSignRequest
import grobase.models.UploadResult

class StorageApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StorageApi
        //val apiInstance = StorageApi()

        // to test storageCreateBucket
        should("test storageCreateBucket") {
            // uncomment below to test storageCreateBucket
            //val name : kotlin.String = name_example // kotlin.String | 
            //val result : StorageCreateBucket200Response = apiInstance.storageCreateBucket(name)
            //result shouldBe ("TODO")
        }

        // to test storageDelete
        should("test storageDelete") {
            // uncomment below to test storageDelete
            //val bucket : kotlin.String = bucket_example // kotlin.String | 
            //val key : kotlin.String = key_example // kotlin.String | 
            //apiInstance.storageDelete(bucket, key)
        }

        // to test storageDownload
        should("test storageDownload") {
            // uncomment below to test storageDownload
            //val bucket : kotlin.String = bucket_example // kotlin.String | 
            //val key : kotlin.String = key_example // kotlin.String | 
            //val result : java.io.File = apiInstance.storageDownload(bucket, key)
            //result shouldBe ("TODO")
        }

        // to test storageList
        should("test storageList") {
            // uncomment below to test storageList
            //val bucket : kotlin.String = bucket_example // kotlin.String | 
            //val prefix : kotlin.String = prefix_example // kotlin.String | 
            //val result : StorageList200Response = apiInstance.storageList(bucket, prefix)
            //result shouldBe ("TODO")
        }

        // to test storageListBuckets
        should("test storageListBuckets") {
            // uncomment below to test storageListBuckets
            //val result : StorageListBuckets200Response = apiInstance.storageListBuckets()
            //result shouldBe ("TODO")
        }

        // to test storageSign
        should("test storageSign") {
            // uncomment below to test storageSign
            //val bucket : kotlin.String = bucket_example // kotlin.String | 
            //val key : kotlin.String = key_example // kotlin.String | 
            //val storageSignRequest : StorageSignRequest =  // StorageSignRequest | 
            //val result : SignedUrl = apiInstance.storageSign(bucket, key, storageSignRequest)
            //result shouldBe ("TODO")
        }

        // to test storageUpload
        should("test storageUpload") {
            // uncomment below to test storageUpload
            //val bucket : kotlin.String = bucket_example // kotlin.String | 
            //val key : kotlin.String = key_example // kotlin.String | 
            //val body : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val result : UploadResult = apiInstance.storageUpload(bucket, key, body)
            //result shouldBe ("TODO")
        }

    }
}
