# coding: utf-8

# flake8: noqa
"""
    Grobase Public API

    Hand-authored, codegen-ready spec for the five public surfaces a client SDK consumes, at the exact Kong-routed paths the `@mini-baas/js` SDK targets (`/auth/v1`, `/rest/v1`, `/storage/v1`, `/query/v1`, `/functions/v1`).  This is the canonical spec for **A4 multi-language SDK codegen** (Python, Dart). It is deliberately separate from the per-service `*.json` documents collected by `openapi-collect.sh`, which describe each NestJS service at its *internal* port/path (not the public Kong prefix). Where a route is gotrue/PostgREST/Deno (not NestJS), only this hand-authored spec describes it — those services emit no `/docs-json`.  Verified against `sdk/src/core/routes.ts` (the SDK's route table) and the live stack on 2026-06-13.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from grobase.models.auth_recover_request import AuthRecoverRequest
from grobase.models.auth_sign_up200_response import AuthSignUp200Response
from grobase.models.bucket_info import BucketInfo
from grobase.models.error import Error
from grobase.models.function_get200_response import FunctionGet200Response
from grobase.models.mfa_challenge_response import MfaChallengeResponse
from grobase.models.mfa_enroll_request import MfaEnrollRequest
from grobase.models.mfa_enroll_response import MfaEnrollResponse
from grobase.models.mfa_enroll_response_totp import MfaEnrollResponseTotp
from grobase.models.mfa_verify_request import MfaVerifyRequest
from grobase.models.query_engines200_response import QueryEngines200Response
from grobase.models.query_request import QueryRequest
from grobase.models.query_response import QueryResponse
from grobase.models.rest_insert_request import RestInsertRequest
from grobase.models.session import Session
from grobase.models.sign_up_request import SignUpRequest
from grobase.models.signed_url import SignedUrl
from grobase.models.storage_create_bucket200_response import StorageCreateBucket200Response
from grobase.models.storage_list200_response import StorageList200Response
from grobase.models.storage_list_buckets200_response import StorageListBuckets200Response
from grobase.models.storage_object import StorageObject
from grobase.models.storage_sign_request import StorageSignRequest
from grobase.models.token_request import TokenRequest
from grobase.models.txn_request import TxnRequest
from grobase.models.txn_request_operations_inner import TxnRequestOperationsInner
from grobase.models.txn_response import TxnResponse
from grobase.models.txn_response_results_inner import TxnResponseResultsInner
from grobase.models.update_user_request import UpdateUserRequest
from grobase.models.upload_result import UploadResult
from grobase.models.user import User
from grobase.models.verify_request import VerifyRequest

