# coding: utf-8

"""
    Grobase Public API

    Hand-authored, codegen-ready spec for the five public surfaces a client SDK consumes, at the exact Kong-routed paths the `@mini-baas/js` SDK targets (`/auth/v1`, `/rest/v1`, `/storage/v1`, `/query/v1`, `/functions/v1`).  This is the canonical spec for **A4 multi-language SDK codegen** (Python, Dart). It is deliberately separate from the per-service `*.json` documents collected by `openapi-collect.sh`, which describe each NestJS service at its *internal* port/path (not the public Kong prefix). Where a route is gotrue/PostgREST/Deno (not NestJS), only this hand-authored spec describes it — those services emit no `/docs-json`.  Verified against `sdk/src/core/routes.ts` (the SDK's route table) and the live stack on 2026-06-13.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StorageSignRequest(BaseModel):
    """
    StorageSignRequest
    """ # noqa: E501
    method: Optional[StrictStr] = None
    expires_in: Optional[StrictInt] = Field(default=None, alias="expiresIn")
    content_type: Optional[StrictStr] = Field(default=None, alias="contentType")
    __properties: ClassVar[List[str]] = ["method", "expiresIn", "contentType"]

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['GET', 'PUT']):
            raise ValueError("must be one of enum values ('GET', 'PUT')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StorageSignRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StorageSignRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "method": obj.get("method"),
            "expiresIn": obj.get("expiresIn"),
            "contentType": obj.get("contentType")
        })
        return _obj


