/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import grobase.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken 
 * @param tokenType 
 * @param expiresIn 
 * @param expiresAt 
 * @param refreshToken 
 * @param user 
 */


data class Session (

    @Json(name = "access_token")
    val accessToken: kotlin.String,

    @Json(name = "token_type")
    val tokenType: kotlin.String? = null,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Int? = null,

    @Json(name = "expires_at")
    val expiresAt: kotlin.Int? = null,

    @Json(name = "refresh_token")
    val refreshToken: kotlin.String? = null,

    @Json(name = "user")
    val user: User? = null

) {


}

