/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import grobase.models.TxnResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param guarantee 
 * @param mount 
 * @param results 
 */


data class TxnResponse (

    @Json(name = "guarantee")
    val guarantee: TxnResponse.Guarantee? = null,

    @Json(name = "mount")
    val mount: kotlin.String? = null,

    @Json(name = "results")
    val results: kotlin.collections.List<TxnResponseResultsInner>? = null

) {

    /**
     * 
     *
     * Values: atomic
     */
    @JsonClass(generateAdapter = false)
    enum class Guarantee(val value: kotlin.String) {
        @Json(name = "atomic") atomic("atomic");
    }

}

