/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param email 
 * @param role 
 * @param aud 
 * @param appMetadata 
 * @param userMetadata 
 * @param createdAt 
 */


data class User (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "role")
    val role: kotlin.String? = null,

    @Json(name = "aud")
    val aud: kotlin.String? = null,

    @Json(name = "app_metadata")
    val appMetadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "user_metadata")
    val userMetadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

