/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param token 
 * @param tokenHash 
 */


data class VerifyRequest (

    @Json(name = "type")
    val type: VerifyRequest.Type,

    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "token_hash")
    val tokenHash: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: signup,recovery,magiclink,email_change
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "signup") signup("signup"),
        @Json(name = "recovery") recovery("recovery"),
        @Json(name = "magiclink") magiclink("magiclink"),
        @Json(name = "email_change") email_change("email_change");
    }

}

