/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.MfaEnrollRequest

class MfaEnrollRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MfaEnrollRequest
        //val modelInstance = MfaEnrollRequest()

        // to test the property `factorType`
        should("test factorType") {
            // uncomment below to test the property
            //modelInstance.factorType shouldBe ("TODO")
        }

        // to test the property `friendlyName`
        should("test friendlyName") {
            // uncomment below to test the property
            //modelInstance.friendlyName shouldBe ("TODO")
        }

        // to test the property `issuer`
        should("test issuer") {
            // uncomment below to test the property
            //modelInstance.issuer shouldBe ("TODO")
        }

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

    }
}
