/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.QueryEngines200Response

class QueryEngines200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryEngines200Response
        //val modelInstance = QueryEngines200Response()

        // to test the property `engines`
        should("test engines") {
            // uncomment below to test the property
            //modelInstance.engines shouldBe ("TODO")
        }

    }
}
