/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.TxnResponse
import grobase.models.TxnResponseResultsInner

class TxnResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TxnResponse
        //val modelInstance = TxnResponse()

        // to test the property `guarantee`
        should("test guarantee") {
            // uncomment below to test the property
            //modelInstance.guarantee shouldBe ("TODO")
        }

        // to test the property `mount`
        should("test mount") {
            // uncomment below to test the property
            //modelInstance.mount shouldBe ("TODO")
        }

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
