/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.TxnRequestOperationsInner

class TxnRequestOperationsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TxnRequestOperationsInner
        //val modelInstance = TxnRequestOperationsInner()

        // to test the property `op`
        should("test op") {
            // uncomment below to test the property
            //modelInstance.op shouldBe ("TODO")
        }

        // to test the property `resource`
        should("test resource") {
            // uncomment below to test the property
            //modelInstance.resource shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `filter`
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

        // to test the property `idempotencyKey`
        should("test idempotencyKey") {
            // uncomment below to test the property
            //modelInstance.idempotencyKey shouldBe ("TODO")
        }

    }
}
