/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.TxnResponseResultsInner

class TxnResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TxnResponseResultsInner
        //val modelInstance = TxnResponseResultsInner()

        // to test the property `op`
        should("test op") {
            // uncomment below to test the property
            //modelInstance.op shouldBe ("TODO")
        }

        // to test the property `resource`
        should("test resource") {
            // uncomment below to test the property
            //modelInstance.resource shouldBe ("TODO")
        }

        // to test the property `rowCount`
        should("test rowCount") {
            // uncomment below to test the property
            //modelInstance.rowCount shouldBe ("TODO")
        }

    }
}
