/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import grobase.models.User

class UserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of User
        //val modelInstance = User()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `role`
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `aud`
        should("test aud") {
            // uncomment below to test the property
            //modelInstance.aud shouldBe ("TODO")
        }

        // to test the property `appMetadata`
        should("test appMetadata") {
            // uncomment below to test the property
            //modelInstance.appMetadata shouldBe ("TODO")
        }

        // to test the property `userMetadata`
        should("test userMetadata") {
            // uncomment below to test the property
            //modelInstance.userMetadata shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
