# coding: utf-8

# flake8: noqa

"""
    Grobase Public API

    Hand-authored, codegen-ready spec for the five public surfaces a client SDK consumes, at the exact Kong-routed paths the `@mini-baas/js` SDK targets (`/auth/v1`, `/rest/v1`, `/storage/v1`, `/query/v1`, `/functions/v1`).  This is the canonical spec for **A4 multi-language SDK codegen** (Python, Dart). It is deliberately separate from the per-service `*.json` documents collected by `openapi-collect.sh`, which describe each NestJS service at its *internal* port/path (not the public Kong prefix). Where a route is gotrue/PostgREST/Deno (not NestJS), only this hand-authored spec describes it — those services emit no `/docs-json`.  Verified against `sdk/src/core/routes.ts` (the SDK's route table) and the live stack on 2026-06-13.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.2.0"

# Define package exports
__all__ = [
    "AuthApi",
    "FunctionsApi",
    "QueryApi",
    "RestApi",
    "StorageApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthRecoverRequest",
    "AuthSignUp200Response",
    "BucketInfo",
    "Error",
    "FunctionGet200Response",
    "MfaChallengeResponse",
    "MfaEnrollRequest",
    "MfaEnrollResponse",
    "MfaEnrollResponseTotp",
    "MfaVerifyRequest",
    "QueryEngines200Response",
    "QueryRequest",
    "QueryResponse",
    "RestInsertRequest",
    "Session",
    "SignUpRequest",
    "SignedUrl",
    "StorageCreateBucket200Response",
    "StorageList200Response",
    "StorageListBuckets200Response",
    "StorageObject",
    "StorageSignRequest",
    "TokenRequest",
    "TxnRequest",
    "TxnRequestOperationsInner",
    "TxnResponse",
    "TxnResponseResultsInner",
    "UpdateUserRequest",
    "UploadResult",
    "User",
    "VerifyRequest",
]

# import apis into sdk package
from grobase.api.auth_api import AuthApi as AuthApi
from grobase.api.functions_api import FunctionsApi as FunctionsApi
from grobase.api.query_api import QueryApi as QueryApi
from grobase.api.rest_api import RestApi as RestApi
from grobase.api.storage_api import StorageApi as StorageApi

# import ApiClient
from grobase.api_response import ApiResponse as ApiResponse
from grobase.api_client import ApiClient as ApiClient
from grobase.configuration import Configuration as Configuration
from grobase.exceptions import OpenApiException as OpenApiException
from grobase.exceptions import ApiTypeError as ApiTypeError
from grobase.exceptions import ApiValueError as ApiValueError
from grobase.exceptions import ApiKeyError as ApiKeyError
from grobase.exceptions import ApiAttributeError as ApiAttributeError
from grobase.exceptions import ApiException as ApiException

# import models into sdk package
from grobase.models.auth_recover_request import AuthRecoverRequest as AuthRecoverRequest
from grobase.models.auth_sign_up200_response import AuthSignUp200Response as AuthSignUp200Response
from grobase.models.bucket_info import BucketInfo as BucketInfo
from grobase.models.error import Error as Error
from grobase.models.function_get200_response import FunctionGet200Response as FunctionGet200Response
from grobase.models.mfa_challenge_response import MfaChallengeResponse as MfaChallengeResponse
from grobase.models.mfa_enroll_request import MfaEnrollRequest as MfaEnrollRequest
from grobase.models.mfa_enroll_response import MfaEnrollResponse as MfaEnrollResponse
from grobase.models.mfa_enroll_response_totp import MfaEnrollResponseTotp as MfaEnrollResponseTotp
from grobase.models.mfa_verify_request import MfaVerifyRequest as MfaVerifyRequest
from grobase.models.query_engines200_response import QueryEngines200Response as QueryEngines200Response
from grobase.models.query_request import QueryRequest as QueryRequest
from grobase.models.query_response import QueryResponse as QueryResponse
from grobase.models.rest_insert_request import RestInsertRequest as RestInsertRequest
from grobase.models.session import Session as Session
from grobase.models.sign_up_request import SignUpRequest as SignUpRequest
from grobase.models.signed_url import SignedUrl as SignedUrl
from grobase.models.storage_create_bucket200_response import StorageCreateBucket200Response as StorageCreateBucket200Response
from grobase.models.storage_list200_response import StorageList200Response as StorageList200Response
from grobase.models.storage_list_buckets200_response import StorageListBuckets200Response as StorageListBuckets200Response
from grobase.models.storage_object import StorageObject as StorageObject
from grobase.models.storage_sign_request import StorageSignRequest as StorageSignRequest
from grobase.models.token_request import TokenRequest as TokenRequest
from grobase.models.txn_request import TxnRequest as TxnRequest
from grobase.models.txn_request_operations_inner import TxnRequestOperationsInner as TxnRequestOperationsInner
from grobase.models.txn_response import TxnResponse as TxnResponse
from grobase.models.txn_response_results_inner import TxnResponseResultsInner as TxnResponseResultsInner
from grobase.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from grobase.models.upload_result import UploadResult as UploadResult
from grobase.models.user import User as User
from grobase.models.verify_request import VerifyRequest as VerifyRequest

