/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param factorType 
 * @param friendlyName 
 * @param issuer 
 * @param phone 
 */


data class MfaEnrollRequest (

    @Json(name = "factor_type")
    val factorType: MfaEnrollRequest.FactorType? = FactorType.totp,

    @Json(name = "friendly_name")
    val friendlyName: kotlin.String? = null,

    @Json(name = "issuer")
    val issuer: kotlin.String? = null,

    @Json(name = "phone")
    val phone: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: totp,phone
     */
    @JsonClass(generateAdapter = false)
    enum class FactorType(val value: kotlin.String) {
        @Json(name = "totp") totp("totp"),
        @Json(name = "phone") phone("phone");
    }

}

