/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models

import grobase.models.MfaEnrollResponseTotp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param friendlyName 
 * @param totp 
 */


data class MfaEnrollResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "type")
    val type: MfaEnrollResponse.Type,

    @Json(name = "friendly_name")
    val friendlyName: kotlin.String? = null,

    @Json(name = "totp")
    val totp: MfaEnrollResponseTotp? = null

) {

    /**
     * 
     *
     * Values: totp,phone
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "totp") totp("totp"),
        @Json(name = "phone") phone("phone");
    }

}

