/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param databaseId 
 * @param action 
 * @param resource 
 * @param payload 
 */


data class QueryRequest (

    @Json(name = "database_id")
    val databaseId: kotlin.String,

    @Json(name = "action")
    val action: kotlin.String,

    @Json(name = "resource")
    val resource: kotlin.String,

    @Json(name = "payload")
    val payload: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

