/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param signedUrl 
 * @param expiresAt 
 * @param method 
 * @param bucket 
 * @param key 
 */


data class SignedUrl (

    @Json(name = "signedUrl")
    val signedUrl: java.net.URI? = null,

    @Json(name = "expiresAt")
    val expiresAt: kotlin.String? = null,

    @Json(name = "method")
    val method: kotlin.String? = null,

    @Json(name = "bucket")
    val bucket: kotlin.String? = null,

    @Json(name = "key")
    val key: kotlin.String? = null

) {


}

