/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key 
 * @param propertySize 
 * @param lastModified 
 * @param etag 
 */


data class StorageObject (

    @Json(name = "key")
    val key: kotlin.String? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "lastModified")
    val lastModified: kotlin.String? = null,

    @Json(name = "etag")
    val etag: kotlin.String? = null

) {


}

