/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param method 
 * @param expiresIn 
 * @param contentType 
 */


data class StorageSignRequest (

    @Json(name = "method")
    val method: StorageSignRequest.Method? = null,

    @Json(name = "expiresIn")
    val expiresIn: kotlin.Int? = null,

    @Json(name = "contentType")
    val contentType: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: GET,PUT
     */
    @JsonClass(generateAdapter = false)
    enum class Method(val value: kotlin.String) {
        @Json(name = "GET") GET("GET"),
        @Json(name = "PUT") PUT("PUT");
    }

}

