/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param op 
 * @param resource 
 * @param `data` 
 * @param filter 
 * @param idempotencyKey 
 */


data class TxnRequestOperationsInner (

    @Json(name = "op")
    val op: TxnRequestOperationsInner.Op,

    @Json(name = "resource")
    val resource: kotlin.String,

    @Json(name = "data")
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "filter")
    val filter: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "idempotencyKey")
    val idempotencyKey: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: insert,update,delete,upsert
     */
    @JsonClass(generateAdapter = false)
    enum class Op(val value: kotlin.String) {
        @Json(name = "insert") insert("insert"),
        @Json(name = "update") update("update"),
        @Json(name = "delete") delete("delete"),
        @Json(name = "upsert") upsert("upsert");
    }

}

