//
// MfaEnrollResponseTotp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MfaEnrollResponseTotp: Codable, JSONEncodable, Hashable {

    public var qrCode: String?
    public var secret: String?
    public var uri: String?

    public init(qrCode: String? = nil, secret: String? = nil, uri: String? = nil) {
        self.qrCode = qrCode
        self.secret = secret
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case qrCode = "qr_code"
        case secret
        case uri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(qrCode, forKey: .qrCode)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(uri, forKey: .uri)
    }
}

