//
// MfaVerifyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MfaVerifyRequest: Codable, JSONEncodable, Hashable {

    public var challengeId: String
    public var code: String

    public init(challengeId: String, code: String) {
        self.challengeId = challengeId
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case challengeId = "challenge_id"
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(challengeId, forKey: .challengeId)
        try container.encode(code, forKey: .code)
    }
}

