//
// QueryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QueryResponse: Codable, JSONEncodable, Hashable {

    public var data: AnyCodable?
    public var count: Int?
    public var meta: [String: AnyCodable]?

    public init(data: AnyCodable? = nil, count: Int? = nil, meta: [String: AnyCodable]? = nil) {
        self.data = data
        self.count = count
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case count
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}

