//
// SignedUrl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignedUrl: Codable, JSONEncodable, Hashable {

    public var signedUrl: String?
    public var expiresAt: String?
    public var method: String?
    public var bucket: String?
    public var key: String?

    public init(signedUrl: String? = nil, expiresAt: String? = nil, method: String? = nil, bucket: String? = nil, key: String? = nil) {
        self.signedUrl = signedUrl
        self.expiresAt = expiresAt
        self.method = method
        self.bucket = bucket
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signedUrl
        case expiresAt
        case method
        case bucket
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(signedUrl, forKey: .signedUrl)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(bucket, forKey: .bucket)
        try container.encodeIfPresent(key, forKey: .key)
    }
}

