//
// StorageObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StorageObject: Codable, JSONEncodable, Hashable {

    public var key: String?
    public var size: Int?
    public var lastModified: String?
    public var etag: String?

    public init(key: String? = nil, size: Int? = nil, lastModified: String? = nil, etag: String? = nil) {
        self.key = key
        self.size = size
        self.lastModified = lastModified
        self.etag = etag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case size
        case lastModified
        case etag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(lastModified, forKey: .lastModified)
        try container.encodeIfPresent(etag, forKey: .etag)
    }
}

