//
// StorageCreateBucket200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StorageCreateBucket200Response: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var created: Bool?

    public init(name: String? = nil, created: Bool? = nil) {
        self.name = name
        self.created = created
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case created
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(created, forKey: .created)
    }
}

