//
// StorageListBuckets200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StorageListBuckets200Response: Codable, JSONEncodable, Hashable {

    public var buckets: [BucketInfo]?

    public init(buckets: [BucketInfo]? = nil) {
        self.buckets = buckets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case buckets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(buckets, forKey: .buckets)
    }
}

