//
// TokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenRequest: Codable, JSONEncodable, Hashable {

    public var email: String
    public var password: String?
    public var refreshToken: String?

    public init(email: String, password: String? = nil, refreshToken: String? = nil) {
        self.email = email
        self.password = password
        self.refreshToken = refreshToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case refreshToken = "refresh_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
    }
}

