//
// TxnResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TxnResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var op: String?
    public var resource: String?
    public var rowCount: Int?

    public init(op: String? = nil, resource: String? = nil, rowCount: Int? = nil) {
        self.op = op
        self.resource = resource
        self.rowCount = rowCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case op
        case resource
        case rowCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(op, forKey: .op)
        try container.encodeIfPresent(resource, forKey: .resource)
        try container.encodeIfPresent(rowCount, forKey: .rowCount)
    }
}

