//
// VerifyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyRequest: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case signup = "signup"
        case recovery = "recovery"
        case magiclink = "magiclink"
        case emailChange = "email_change"
    }
    public var type: ModelType
    public var token: String?
    public var tokenHash: String?

    public init(type: ModelType, token: String? = nil, tokenHash: String? = nil) {
        self.type = type
        self.token = token
        self.tokenHash = tokenHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case token
        case tokenHash = "token_hash"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(tokenHash, forKey: .tokenHash)
    }
}

