# coding: utf-8

"""
    Grobase Public API

    Hand-authored, codegen-ready spec for the five public surfaces a client SDK consumes, at the exact Kong-routed paths the `@mini-baas/js` SDK targets (`/auth/v1`, `/rest/v1`, `/storage/v1`, `/query/v1`, `/functions/v1`).  This is the canonical spec for **A4 multi-language SDK codegen** (Python, Dart). It is deliberately separate from the per-service `*.json` documents collected by `openapi-collect.sh`, which describe each NestJS service at its *internal* port/path (not the public Kong prefix). Where a route is gotrue/PostgREST/Deno (not NestJS), only this hand-authored spec describes it — those services emit no `/docs-json`.  Verified against `sdk/src/core/routes.ts` (the SDK's route table) and the live stack on 2026-06-13.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grobase.api.rest_api import RestApi


class TestRestApi(unittest.TestCase):
    """RestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RestApi()

    def tearDown(self) -> None:
        pass

    def test_rest_delete(self) -> None:
        """Test case for rest_delete

        Delete rows matching the filter.
        """
        pass

    def test_rest_insert(self) -> None:
        """Test case for rest_insert

        Insert one or many rows.
        """
        pass

    def test_rest_rpc(self) -> None:
        """Test case for rest_rpc

        Call a Postgres stored function (PostgREST RPC).
        """
        pass

    def test_rest_select(self) -> None:
        """Test case for rest_select

        Select rows (PostgREST filters via query params).
        """
        pass

    def test_rest_update(self) -> None:
        """Test case for rest_update

        Update rows matching the filter.
        """
        pass


if __name__ == '__main__':
    unittest.main()
