# coding: utf-8

"""
    Grobase Public API

    Hand-authored, codegen-ready spec for the five public surfaces a client SDK consumes, at the exact Kong-routed paths the `@mini-baas/js` SDK targets (`/auth/v1`, `/rest/v1`, `/storage/v1`, `/query/v1`, `/functions/v1`).  This is the canonical spec for **A4 multi-language SDK codegen** (Python, Dart). It is deliberately separate from the per-service `*.json` documents collected by `openapi-collect.sh`, which describe each NestJS service at its *internal* port/path (not the public Kong prefix). Where a route is gotrue/PostgREST/Deno (not NestJS), only this hand-authored spec describes it — those services emit no `/docs-json`.  Verified against `sdk/src/core/routes.ts` (the SDK's route table) and the live stack on 2026-06-13.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grobase.models.error import Error

class TestError(unittest.TestCase):
    """Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Error:
        """Test Error
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Error`
        """
        model = Error()
        if include_optional:
            return Error(
                message = '',
                error = '',
                status = 56
            )
        else:
            return Error(
        )
        """

    def testError(self):
        """Test Error"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
