# coding: utf-8

"""
    Grobase Public API

    Hand-authored, codegen-ready spec for the five public surfaces a client SDK consumes, at the exact Kong-routed paths the `@mini-baas/js` SDK targets (`/auth/v1`, `/rest/v1`, `/storage/v1`, `/query/v1`, `/functions/v1`).  This is the canonical spec for **A4 multi-language SDK codegen** (Python, Dart). It is deliberately separate from the per-service `*.json` documents collected by `openapi-collect.sh`, which describe each NestJS service at its *internal* port/path (not the public Kong prefix). Where a route is gotrue/PostgREST/Deno (not NestJS), only this hand-authored spec describes it — those services emit no `/docs-json`.  Verified against `sdk/src/core/routes.ts` (the SDK's route table) and the live stack on 2026-06-13.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grobase.api.functions_api import FunctionsApi


class TestFunctionsApi(unittest.TestCase):
    """FunctionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FunctionsApi()

    def tearDown(self) -> None:
        pass

    def test_function_delete(self) -> None:
        """Test case for function_delete

        Delete a deployed function.
        """
        pass

    def test_function_get(self) -> None:
        """Test case for function_get

        Get a deployed function's source.
        """
        pass

    def test_function_invoke(self) -> None:
        """Test case for function_invoke

        Invoke a deployed edge function.
        """
        pass


if __name__ == '__main__':
    unittest.main()
