/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import grobase.models.AuthRecoverRequest
import grobase.models.AuthSignUp200Response
import grobase.models.Error
import grobase.models.MfaChallengeResponse
import grobase.models.MfaEnrollRequest
import grobase.models.MfaEnrollResponse
import grobase.models.MfaVerifyRequest
import grobase.models.Session
import grobase.models.SignUpRequest
import grobase.models.TokenRequest
import grobase.models.UpdateUserRequest
import grobase.models.User
import grobase.models.VerifyRequest

import com.squareup.moshi.Json

import grobase.infrastructure.ApiClient
import grobase.infrastructure.ApiResponse
import grobase.infrastructure.ClientException
import grobase.infrastructure.ClientError
import grobase.infrastructure.ServerException
import grobase.infrastructure.ServerError
import grobase.infrastructure.MultiValueMap
import grobase.infrastructure.PartConfig
import grobase.infrastructure.RequestConfig
import grobase.infrastructure.RequestMethod
import grobase.infrastructure.ResponseType
import grobase.infrastructure.Success
import grobase.infrastructure.toMultiValue

open class AuthApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://127.0.0.1:8002")
        }
    }

    /**
     * GET /auth/v1/authorize
     * Begin a social/OIDC OAuth flow (302 to the provider).
     * The SDK&#39;s &#x60;auth.signInWithOAuth()&#x60; builds this URL; the browser is redirected here, gotrue 302s to the provider, then back to &#x60;redirect_to&#x60;.
     * @param provider 
     * @param redirectTo  (optional)
     * @param scopes  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authAuthorize(provider: kotlin.String, redirectTo: java.net.URI? = null, scopes: kotlin.String? = null) : Unit {
        val localVarResponse = authAuthorizeWithHttpInfo(provider = provider, redirectTo = redirectTo, scopes = scopes)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /auth/v1/authorize
     * Begin a social/OIDC OAuth flow (302 to the provider).
     * The SDK&#39;s &#x60;auth.signInWithOAuth()&#x60; builds this URL; the browser is redirected here, gotrue 302s to the provider, then back to &#x60;redirect_to&#x60;.
     * @param provider 
     * @param redirectTo  (optional)
     * @param scopes  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun authAuthorizeWithHttpInfo(provider: kotlin.String, redirectTo: java.net.URI?, scopes: kotlin.String?) : ApiResponse<Unit?> {
        val localVariableConfig = authAuthorizeRequestConfig(provider = provider, redirectTo = redirectTo, scopes = scopes)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation authAuthorize
     *
     * @param provider 
     * @param redirectTo  (optional)
     * @param scopes  (optional)
     * @return RequestConfig
     */
    fun authAuthorizeRequestConfig(provider: kotlin.String, redirectTo: java.net.URI?, scopes: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("provider", listOf(provider.toString()))
                if (redirectTo != null) {
                    put("redirect_to", listOf(redirectTo.toString()))
                }
                if (scopes != null) {
                    put("scopes", listOf(scopes.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/auth/v1/authorize",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /auth/v1/user
     * Get the authenticated user.
     * 
     * @return User
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authGetUser() : User {
        val localVarResponse = authGetUserWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as User
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /auth/v1/user
     * Get the authenticated user.
     * 
     * @return ApiResponse<User?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun authGetUserWithHttpInfo() : ApiResponse<User?> {
        val localVariableConfig = authGetUserRequestConfig()

        return request<Unit, User>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation authGetUser
     *
     * @return RequestConfig
     */
    fun authGetUserRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/auth/v1/user",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /auth/v1/logout
     * Revoke the current session.
     * 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authLogout() : Unit {
        val localVarResponse = authLogoutWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/logout
     * Revoke the current session.
     * 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun authLogoutWithHttpInfo() : ApiResponse<Unit?> {
        val localVariableConfig = authLogoutRequestConfig()

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation authLogout
     *
     * @return RequestConfig
     */
    fun authLogoutRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/logout",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /auth/v1/recover
     * Send a password-recovery email.
     * 
     * @param authRecoverRequest 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authRecover(authRecoverRequest: AuthRecoverRequest) : Unit {
        val localVarResponse = authRecoverWithHttpInfo(authRecoverRequest = authRecoverRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/recover
     * Send a password-recovery email.
     * 
     * @param authRecoverRequest 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun authRecoverWithHttpInfo(authRecoverRequest: AuthRecoverRequest) : ApiResponse<Unit?> {
        val localVariableConfig = authRecoverRequestConfig(authRecoverRequest = authRecoverRequest)

        return request<AuthRecoverRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation authRecover
     *
     * @param authRecoverRequest 
     * @return RequestConfig
     */
    fun authRecoverRequestConfig(authRecoverRequest: AuthRecoverRequest) : RequestConfig<AuthRecoverRequest> {
        val localVariableBody = authRecoverRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/recover",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /auth/v1/signup
     * Register a new user (email + password).
     * 
     * @param signUpRequest 
     * @return AuthSignUp200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authSignUp(signUpRequest: SignUpRequest) : AuthSignUp200Response {
        val localVarResponse = authSignUpWithHttpInfo(signUpRequest = signUpRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AuthSignUp200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/signup
     * Register a new user (email + password).
     * 
     * @param signUpRequest 
     * @return ApiResponse<AuthSignUp200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun authSignUpWithHttpInfo(signUpRequest: SignUpRequest) : ApiResponse<AuthSignUp200Response?> {
        val localVariableConfig = authSignUpRequestConfig(signUpRequest = signUpRequest)

        return request<SignUpRequest, AuthSignUp200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation authSignUp
     *
     * @param signUpRequest 
     * @return RequestConfig
     */
    fun authSignUpRequestConfig(signUpRequest: SignUpRequest) : RequestConfig<SignUpRequest> {
        val localVariableBody = signUpRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/signup",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter grantType
     */
     enum class GrantTypeAuthToken(val value: kotlin.String) {
         @Json(name = "password") password("password"),
         @Json(name = "refresh_token") refresh_token("refresh_token");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * POST /auth/v1/token
     * Exchange credentials for a session (password or refresh_token grant).
     * 
     * @param grantType 
     * @param tokenRequest 
     * @return Session
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authToken(grantType: GrantTypeAuthToken, tokenRequest: TokenRequest) : Session {
        val localVarResponse = authTokenWithHttpInfo(grantType = grantType, tokenRequest = tokenRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Session
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/token
     * Exchange credentials for a session (password or refresh_token grant).
     * 
     * @param grantType 
     * @param tokenRequest 
     * @return ApiResponse<Session?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun authTokenWithHttpInfo(grantType: GrantTypeAuthToken, tokenRequest: TokenRequest) : ApiResponse<Session?> {
        val localVariableConfig = authTokenRequestConfig(grantType = grantType, tokenRequest = tokenRequest)

        return request<TokenRequest, Session>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation authToken
     *
     * @param grantType 
     * @param tokenRequest 
     * @return RequestConfig
     */
    fun authTokenRequestConfig(grantType: GrantTypeAuthToken, tokenRequest: TokenRequest) : RequestConfig<TokenRequest> {
        val localVariableBody = tokenRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("grant_type", listOf(grantType.value))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/token",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /auth/v1/user
     * Update the authenticated user (email / password / metadata).
     * 
     * @param updateUserRequest 
     * @return User
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authUpdateUser(updateUserRequest: UpdateUserRequest) : User {
        val localVarResponse = authUpdateUserWithHttpInfo(updateUserRequest = updateUserRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as User
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/user
     * Update the authenticated user (email / password / metadata).
     * 
     * @param updateUserRequest 
     * @return ApiResponse<User?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun authUpdateUserWithHttpInfo(updateUserRequest: UpdateUserRequest) : ApiResponse<User?> {
        val localVariableConfig = authUpdateUserRequestConfig(updateUserRequest = updateUserRequest)

        return request<UpdateUserRequest, User>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation authUpdateUser
     *
     * @param updateUserRequest 
     * @return RequestConfig
     */
    fun authUpdateUserRequestConfig(updateUserRequest: UpdateUserRequest) : RequestConfig<UpdateUserRequest> {
        val localVariableBody = updateUserRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/user",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /auth/v1/verify
     * Verify a signup/recovery/magiclink token.
     * 
     * @param verifyRequest 
     * @return AuthSignUp200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authVerify(verifyRequest: VerifyRequest) : AuthSignUp200Response {
        val localVarResponse = authVerifyWithHttpInfo(verifyRequest = verifyRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AuthSignUp200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/verify
     * Verify a signup/recovery/magiclink token.
     * 
     * @param verifyRequest 
     * @return ApiResponse<AuthSignUp200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun authVerifyWithHttpInfo(verifyRequest: VerifyRequest) : ApiResponse<AuthSignUp200Response?> {
        val localVariableConfig = authVerifyRequestConfig(verifyRequest = verifyRequest)

        return request<VerifyRequest, AuthSignUp200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation authVerify
     *
     * @param verifyRequest 
     * @return RequestConfig
     */
    fun authVerifyRequestConfig(verifyRequest: VerifyRequest) : RequestConfig<VerifyRequest> {
        val localVariableBody = verifyRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/verify",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /auth/v1/factors/{factorId}/challenge
     * Open a verification challenge for an enrolled factor.
     * 
     * @param factorId 
     * @return MfaChallengeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun mfaChallenge(factorId: kotlin.String) : MfaChallengeResponse {
        val localVarResponse = mfaChallengeWithHttpInfo(factorId = factorId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MfaChallengeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/factors/{factorId}/challenge
     * Open a verification challenge for an enrolled factor.
     * 
     * @param factorId 
     * @return ApiResponse<MfaChallengeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun mfaChallengeWithHttpInfo(factorId: kotlin.String) : ApiResponse<MfaChallengeResponse?> {
        val localVariableConfig = mfaChallengeRequestConfig(factorId = factorId)

        return request<Unit, MfaChallengeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation mfaChallenge
     *
     * @param factorId 
     * @return RequestConfig
     */
    fun mfaChallengeRequestConfig(factorId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/factors/{factorId}/challenge".replace("{"+"factorId"+"}", encodeURIComponent(factorId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /auth/v1/factors
     * Enroll an MFA factor (TOTP or phone).
     * 
     * @param mfaEnrollRequest 
     * @return MfaEnrollResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun mfaEnroll(mfaEnrollRequest: MfaEnrollRequest) : MfaEnrollResponse {
        val localVarResponse = mfaEnrollWithHttpInfo(mfaEnrollRequest = mfaEnrollRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MfaEnrollResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/factors
     * Enroll an MFA factor (TOTP or phone).
     * 
     * @param mfaEnrollRequest 
     * @return ApiResponse<MfaEnrollResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun mfaEnrollWithHttpInfo(mfaEnrollRequest: MfaEnrollRequest) : ApiResponse<MfaEnrollResponse?> {
        val localVariableConfig = mfaEnrollRequestConfig(mfaEnrollRequest = mfaEnrollRequest)

        return request<MfaEnrollRequest, MfaEnrollResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation mfaEnroll
     *
     * @param mfaEnrollRequest 
     * @return RequestConfig
     */
    fun mfaEnrollRequestConfig(mfaEnrollRequest: MfaEnrollRequest) : RequestConfig<MfaEnrollRequest> {
        val localVariableBody = mfaEnrollRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/factors",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /auth/v1/factors/{factorId}
     * Remove an MFA factor.
     * 
     * @param factorId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun mfaUnenroll(factorId: kotlin.String) : Unit {
        val localVarResponse = mfaUnenrollWithHttpInfo(factorId = factorId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /auth/v1/factors/{factorId}
     * Remove an MFA factor.
     * 
     * @param factorId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun mfaUnenrollWithHttpInfo(factorId: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = mfaUnenrollRequestConfig(factorId = factorId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation mfaUnenroll
     *
     * @param factorId 
     * @return RequestConfig
     */
    fun mfaUnenrollRequestConfig(factorId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/auth/v1/factors/{factorId}".replace("{"+"factorId"+"}", encodeURIComponent(factorId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /auth/v1/factors/{factorId}/verify
     * Verify a challenge with a code; on success upgrades the session AAL.
     * 
     * @param factorId 
     * @param mfaVerifyRequest 
     * @return Session
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun mfaVerify(factorId: kotlin.String, mfaVerifyRequest: MfaVerifyRequest) : Session {
        val localVarResponse = mfaVerifyWithHttpInfo(factorId = factorId, mfaVerifyRequest = mfaVerifyRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Session
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/v1/factors/{factorId}/verify
     * Verify a challenge with a code; on success upgrades the session AAL.
     * 
     * @param factorId 
     * @param mfaVerifyRequest 
     * @return ApiResponse<Session?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun mfaVerifyWithHttpInfo(factorId: kotlin.String, mfaVerifyRequest: MfaVerifyRequest) : ApiResponse<Session?> {
        val localVariableConfig = mfaVerifyRequestConfig(factorId = factorId, mfaVerifyRequest = mfaVerifyRequest)

        return request<MfaVerifyRequest, Session>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation mfaVerify
     *
     * @param factorId 
     * @param mfaVerifyRequest 
     * @return RequestConfig
     */
    fun mfaVerifyRequestConfig(factorId: kotlin.String, mfaVerifyRequest: MfaVerifyRequest) : RequestConfig<MfaVerifyRequest> {
        val localVariableBody = mfaVerifyRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/v1/factors/{factorId}/verify".replace("{"+"factorId"+"}", encodeURIComponent(factorId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
