/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package grobase.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import grobase.models.Error
import grobase.models.SignedUrl
import grobase.models.StorageCreateBucket200Response
import grobase.models.StorageList200Response
import grobase.models.StorageListBuckets200Response
import grobase.models.StorageSignRequest
import grobase.models.UploadResult

import com.squareup.moshi.Json

import grobase.infrastructure.ApiClient
import grobase.infrastructure.ApiResponse
import grobase.infrastructure.ClientException
import grobase.infrastructure.ClientError
import grobase.infrastructure.ServerException
import grobase.infrastructure.ServerError
import grobase.infrastructure.MultiValueMap
import grobase.infrastructure.PartConfig
import grobase.infrastructure.RequestConfig
import grobase.infrastructure.RequestMethod
import grobase.infrastructure.ResponseType
import grobase.infrastructure.Success
import grobase.infrastructure.toMultiValue

open class StorageApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://127.0.0.1:8002")
        }
    }

    /**
     * POST /storage/v1/bucket/{name}
     * Create a bucket.
     * 
     * @param name 
     * @return StorageCreateBucket200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun storageCreateBucket(name: kotlin.String) : StorageCreateBucket200Response {
        val localVarResponse = storageCreateBucketWithHttpInfo(name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StorageCreateBucket200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /storage/v1/bucket/{name}
     * Create a bucket.
     * 
     * @param name 
     * @return ApiResponse<StorageCreateBucket200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun storageCreateBucketWithHttpInfo(name: kotlin.String) : ApiResponse<StorageCreateBucket200Response?> {
        val localVariableConfig = storageCreateBucketRequestConfig(name = name)

        return request<Unit, StorageCreateBucket200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storageCreateBucket
     *
     * @param name 
     * @return RequestConfig
     */
    fun storageCreateBucketRequestConfig(name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/storage/v1/bucket/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /storage/v1/object/{bucket}/{key}
     * Delete an object.
     * 
     * @param bucket 
     * @param key 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun storageDelete(bucket: kotlin.String, key: kotlin.String) : Unit {
        val localVarResponse = storageDeleteWithHttpInfo(bucket = bucket, key = key)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /storage/v1/object/{bucket}/{key}
     * Delete an object.
     * 
     * @param bucket 
     * @param key 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun storageDeleteWithHttpInfo(bucket: kotlin.String, key: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = storageDeleteRequestConfig(bucket = bucket, key = key)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storageDelete
     *
     * @param bucket 
     * @param key 
     * @return RequestConfig
     */
    fun storageDeleteRequestConfig(bucket: kotlin.String, key: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/storage/v1/object/{bucket}/{key}".replace("{"+"bucket"+"}", encodeURIComponent(bucket.toString())).replace("{"+"key"+"}", encodeURIComponent(key.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /storage/v1/object/{bucket}/{key}
     * Download object bytes (owner-scoped).
     * 
     * @param bucket 
     * @param key 
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun storageDownload(bucket: kotlin.String, key: kotlin.String) : java.io.File {
        val localVarResponse = storageDownloadWithHttpInfo(bucket = bucket, key = key)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /storage/v1/object/{bucket}/{key}
     * Download object bytes (owner-scoped).
     * 
     * @param bucket 
     * @param key 
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun storageDownloadWithHttpInfo(bucket: kotlin.String, key: kotlin.String) : ApiResponse<java.io.File?> {
        val localVariableConfig = storageDownloadRequestConfig(bucket = bucket, key = key)

        return request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storageDownload
     *
     * @param bucket 
     * @param key 
     * @return RequestConfig
     */
    fun storageDownloadRequestConfig(bucket: kotlin.String, key: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/octet-stream, application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/storage/v1/object/{bucket}/{key}".replace("{"+"bucket"+"}", encodeURIComponent(bucket.toString())).replace("{"+"key"+"}", encodeURIComponent(key.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /storage/v1/list/{bucket}
     * List objects under a prefix (owner-scoped).
     * 
     * @param bucket 
     * @param prefix  (optional)
     * @return StorageList200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun storageList(bucket: kotlin.String, prefix: kotlin.String? = null) : StorageList200Response {
        val localVarResponse = storageListWithHttpInfo(bucket = bucket, prefix = prefix)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StorageList200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /storage/v1/list/{bucket}
     * List objects under a prefix (owner-scoped).
     * 
     * @param bucket 
     * @param prefix  (optional)
     * @return ApiResponse<StorageList200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun storageListWithHttpInfo(bucket: kotlin.String, prefix: kotlin.String?) : ApiResponse<StorageList200Response?> {
        val localVariableConfig = storageListRequestConfig(bucket = bucket, prefix = prefix)

        return request<Unit, StorageList200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storageList
     *
     * @param bucket 
     * @param prefix  (optional)
     * @return RequestConfig
     */
    fun storageListRequestConfig(bucket: kotlin.String, prefix: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (prefix != null) {
                    put("prefix", listOf(prefix.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/storage/v1/list/{bucket}".replace("{"+"bucket"+"}", encodeURIComponent(bucket.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /storage/v1/bucket
     * List buckets.
     * 
     * @return StorageListBuckets200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun storageListBuckets() : StorageListBuckets200Response {
        val localVarResponse = storageListBucketsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StorageListBuckets200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /storage/v1/bucket
     * List buckets.
     * 
     * @return ApiResponse<StorageListBuckets200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun storageListBucketsWithHttpInfo() : ApiResponse<StorageListBuckets200Response?> {
        val localVariableConfig = storageListBucketsRequestConfig()

        return request<Unit, StorageListBuckets200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storageListBuckets
     *
     * @return RequestConfig
     */
    fun storageListBucketsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/storage/v1/bucket",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /storage/v1/sign/{bucket}/{key}
     * Create a presigned URL (PUT or GET, TTL-clamped).
     * 
     * @param bucket 
     * @param key 
     * @param storageSignRequest  (optional)
     * @return SignedUrl
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun storageSign(bucket: kotlin.String, key: kotlin.String, storageSignRequest: StorageSignRequest? = null) : SignedUrl {
        val localVarResponse = storageSignWithHttpInfo(bucket = bucket, key = key, storageSignRequest = storageSignRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SignedUrl
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /storage/v1/sign/{bucket}/{key}
     * Create a presigned URL (PUT or GET, TTL-clamped).
     * 
     * @param bucket 
     * @param key 
     * @param storageSignRequest  (optional)
     * @return ApiResponse<SignedUrl?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun storageSignWithHttpInfo(bucket: kotlin.String, key: kotlin.String, storageSignRequest: StorageSignRequest?) : ApiResponse<SignedUrl?> {
        val localVariableConfig = storageSignRequestConfig(bucket = bucket, key = key, storageSignRequest = storageSignRequest)

        return request<StorageSignRequest, SignedUrl>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storageSign
     *
     * @param bucket 
     * @param key 
     * @param storageSignRequest  (optional)
     * @return RequestConfig
     */
    fun storageSignRequestConfig(bucket: kotlin.String, key: kotlin.String, storageSignRequest: StorageSignRequest?) : RequestConfig<StorageSignRequest> {
        val localVariableBody = storageSignRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/storage/v1/sign/{bucket}/{key}".replace("{"+"bucket"+"}", encodeURIComponent(bucket.toString())).replace("{"+"key"+"}", encodeURIComponent(key.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /storage/v1/object/{bucket}/{key}
     * Upload (owner-prefixed) — body is the raw object bytes.
     * 
     * @param bucket 
     * @param key 
     * @param body 
     * @return UploadResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun storageUpload(bucket: kotlin.String, key: kotlin.String, body: java.io.File) : UploadResult {
        val localVarResponse = storageUploadWithHttpInfo(bucket = bucket, key = key, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as UploadResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /storage/v1/object/{bucket}/{key}
     * Upload (owner-prefixed) — body is the raw object bytes.
     * 
     * @param bucket 
     * @param key 
     * @param body 
     * @return ApiResponse<UploadResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun storageUploadWithHttpInfo(bucket: kotlin.String, key: kotlin.String, body: java.io.File) : ApiResponse<UploadResult?> {
        val localVariableConfig = storageUploadRequestConfig(bucket = bucket, key = key, body = body)

        return request<java.io.File, UploadResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storageUpload
     *
     * @param bucket 
     * @param key 
     * @param body 
     * @return RequestConfig
     */
    fun storageUploadRequestConfig(bucket: kotlin.String, key: kotlin.String, body: java.io.File) : RequestConfig<java.io.File> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/octet-stream"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/storage/v1/object/{bucket}/{key}".replace("{"+"bucket"+"}", encodeURIComponent(bucket.toString())).replace("{"+"key"+"}", encodeURIComponent(key.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
