#!/usr/bin/env python3
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    gen-deploy.py                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dlesieur <dlesieur@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/06/03 00:00:00 by dlesieur          #+#    #+#              #
#    Updated: 2026/06/03 00:00:00 by dlesieur         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
"""G11 — compile the edition manifest into non-Compose packaging.

Single source of truth, zero duplication:
  * edition topology (plane->profiles, edition->planes) is parsed from the
    Makefile MANIFEST block (the same maps that drive `make up EDITION=`).
  * per-service facts (image, ports, resources, healthcheck, profiles) are
    parsed from docker-compose.yml (the dev runtime).

It emits, all derived (never hand-edited):
  * deploy/edition-manifest.yaml   — resolved planes/editions/service-sets.
  * deploy/helm/mini-baas/values.yaml + values-<edition>.yaml overlays.
  * deploy/kustomize/overlays/<edition>/ — manifest-driven service selection.

A service belongs to an edition iff it is profile-less (core, always on) or
its compose profiles intersect the edition's profiles — exactly how
`docker compose --profile` selects it, so K8s editions match Compose editions
by construction.
"""
from __future__ import annotations
import os
import re
import sys
import yaml

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MAKEFILE = os.path.join(ROOT, "Makefile")
COMPOSE = os.path.join(ROOT, "docker-compose.yml")
DEPLOY = os.path.join(ROOT, "deploy")
HELM = os.path.join(DEPLOY, "helm", "mini-baas")
KUSTOMIZE = os.path.join(DEPLOY, "kustomize")
REGISTRY = os.environ.get("DEPLOY_REGISTRY", "ghcr.io/les-baas")  # also Helm global.imageRegistry
TAG = os.environ.get("DEPLOY_TAG", "latest")

GEN_HEADER = "# GENERATED by scripts/gen-deploy.py from the Makefile manifest + docker-compose.yml.\n# Do not edit by hand — run `make deploy-gen`.\n"


# --------------------------------------------------------------------------- #
#  Parse the Makefile MANIFEST (plane->profiles, edition->planes)
# --------------------------------------------------------------------------- #
def _logical_lines(txt: str) -> list[str]:
    """Collapse Makefile `\\`-continuations into one logical line each."""
    out, buf = [], ""
    for line in txt.splitlines():
        buf = (buf + " " + line.strip()) if buf else line
        if buf.rstrip().endswith("\\"):
            buf = buf.rstrip()[:-1]
        else:
            out.append(buf)
            buf = ""
    if buf:
        out.append(buf)
    return out


def parse_makefile() -> tuple[dict, dict]:
    lines = _logical_lines(open(MAKEFILE, encoding="utf-8").read())

    def val(name: str) -> str | None:
        # Horizontal-whitespace only ([ \t], not \s) so an empty `NAME :=` never
        # bleeds into the next line; strip any trailing inline comment.
        for ln in lines:
            m = re.match(rf"[ \t]*{re.escape(name)}[ \t]*:=[ \t]*(.*)$", ln)
            if m:
                return re.sub(r"#.*$", "", m.group(1)).strip()
        return None

    planes = (val("PLANES") or "").split()
    profiles = {p: (val(f"PROFILES_{p}") or "").split() for p in planes}

    editions = {}
    for e in (val("EDITIONS") or "").split():
        raw = val(f"EDITION_{e}") or ""
        if "filter-out" in raw:  # $(filter-out playground,$(PLANES))
            drop = re.search(r"filter-out\s+([^,]+),", raw).group(1).split()
            editions[e] = [pl for pl in planes if pl not in drop]
        else:
            editions[e] = raw.split()
    return profiles, editions


# --------------------------------------------------------------------------- #
#  Parse docker-compose.yml into per-service deploy facts
# --------------------------------------------------------------------------- #
def parse_mem(v) -> str | None:
    if v is None:
        return None
    s = str(v).strip().lower()
    m = re.match(r"^(\d+(?:\.\d+)?)\s*([kmg]?)b?$", s)
    if not m:
        return None
    n, unit = float(m.group(1)), m.group(2)
    mib = {"k": n / 1024, "m": n, "g": n * 1024, "": n / (1024 * 1024)}[unit]
    return f"{int(round(mib))}Mi"


def parse_cpu(v) -> str | None:
    if v is None:
        return None
    try:
        return f"{int(round(float(v) * 1000))}m"
    except (TypeError, ValueError):
        return None


def container_ports(ports) -> list[int]:
    out = []
    for entry in ports or []:
        s = str(entry).split("/")[0]
        target = s.split(":")[-1]
        target = re.sub(r"\$\{[^}]*\}", "", target) or s.split(":")[-1]
        m = re.search(r"(\d+)", target)
        if m:
            out.append(int(m.group(1)))
    return sorted(set(out))


def to_probe(hc) -> dict | None:
    if not hc or "test" not in hc:
        return None
    test = hc["test"]
    if isinstance(test, str):
        cmd = ["sh", "-c", test]
    elif test and test[0] == "CMD-SHELL":
        cmd = ["sh", "-c", " ".join(test[1:])]
    elif test and test[0] == "CMD":
        cmd = test[1:]
    else:
        cmd = test
    dur = lambda k, d: int(re.sub(r"\D", "", str(hc.get(k, d))) or d)
    return {
        "exec": cmd,
        "initialDelaySeconds": dur("start_period", 10),
        "periodSeconds": dur("interval", 10),
        "timeoutSeconds": dur("timeout", 3),
        "failureThreshold": int(hc.get("retries", 3)),
    }


def parse_compose():
    doc = yaml.safe_load(open(COMPOSE, encoding="utf-8"))
    services = {}
    for name, spec in (doc.get("services") or {}).items():
        if not isinstance(spec, dict):
            continue
        image = spec.get("image")
        if not image:
            image = f"{REGISTRY}/mini-baas-{name}:latest"  # locally-built service
        svc = {
            "enabled": False,
            "image": image,
            "replicas": 1,
            "profiles": sorted(spec.get("profiles", []) or []),
            "ports": container_ports(spec.get("ports")),
        }
        res = {}
        if (mem := parse_mem(spec.get("mem_limit"))):
            res.setdefault("limits", {})["memory"] = mem
            res.setdefault("requests", {})["memory"] = parse_mem(
                str(float(re.sub(r"\D", "", mem)) / 2)) or mem
        if (cpu := parse_cpu(spec.get("cpus"))):
            res.setdefault("limits", {})["cpu"] = cpu
            res.setdefault("requests", {})["cpu"] = parse_cpu(float(re.sub(r"\D", "", cpu)) / 2000) or cpu
        if res:
            svc["resources"] = res
        if (probe := to_probe(spec.get("healthcheck"))):
            svc["probe"] = probe
        services[name] = svc
    return services


# --------------------------------------------------------------------------- #
#  Resolve edition -> profiles -> services
# --------------------------------------------------------------------------- #
def edition_profiles(planes_of_edition, profiles) -> list[str]:
    out = set()
    for plane in planes_of_edition:
        out.update(profiles.get(plane, []))
    return sorted(out)


def services_for(profs, services) -> list[str]:
    enabled = []
    for name, svc in services.items():
        if not svc["profiles"] or (set(svc["profiles"]) & set(profs)):
            enabled.append(name)
    return sorted(enabled)


def dump(path, obj, header=True):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        if header:
            fh.write(GEN_HEADER)
        yaml.safe_dump(obj, fh, sort_keys=True, default_flow_style=False, width=100)


def main() -> int:
    profiles, editions = parse_makefile()
    services = parse_compose()
    core = sorted(n for n, s in services.items() if not s["profiles"])

    ed_profiles = {e: edition_profiles(pl, profiles) for e, pl in editions.items()}
    ed_services = {e: services_for(pr, services) for e, pr in ed_profiles.items()}

    # 1) the resolved manifest
    dump(os.path.join(DEPLOY, "edition-manifest.yaml"), {
        "planeProfiles": profiles,
        "editionPlanes": editions,
        "editionProfiles": ed_profiles,
        "coreServices": core,
        "editionServices": ed_services,
    })

    # 2) Helm base values — core enabled, everything else off until an overlay.
    #    The global pod/container securityContext + namespace + networkPolicy
    #    blocks mirror the hardened ../grobase chart so the generated chart is
    #    secure-by-default (Checkov CKV_K8S_20/21/23/28/29/30/31/37/40 +
    #    CKV2_K8S_6). All are values-driven so a deploy can still override them
    #    (e.g. a DB that needs a writable rootfs sets readOnlyRootFilesystem off).
    base = dict(services)
    for n in core:
        base[n]["enabled"] = True
    dump(os.path.join(HELM, "values.yaml"), {
        "global": {
            "imageRegistry": REGISTRY,
            "imageTag": "latest",
            "nameOverride": "mini-baas",
            "imagePullPolicy": "IfNotPresent",
            # Applied to every pod: run as a high, non-root UID with a seccomp
            # profile (mirrors grobase global.podSecurityContext).
            "podSecurityContext": {
                "runAsNonRoot": True,
                "runAsUser": 10001,
                "runAsGroup": 10001,
                "fsGroup": 10001,
                "seccompProfile": {"type": "RuntimeDefault"},
            },
            # Applied to every container: no privilege escalation, drop every
            # Linux capability (mirrors grobase global.containerSecurityContext).
            # readOnlyRootFilesystem is intentionally NOT set globally: many
            # services here are databases/caches that write to their rootfs; set
            # it per service when the workload tolerates it.
            "containerSecurityContext": {
                "allowPrivilegeEscalation": False,
                "privileged": False,
                "capabilities": {"drop": ["ALL"]},
            },
        },
        # Namespace: rendered onto every object so the chart never lands in the
        # `default` namespace (Checkov CKV_K8S_21). Empty `namespace` defers to
        # `helm --namespace`/.Release.Namespace; set it to pin one. When neither
        # is given (e.g. a bare `helm template`), the chart falls back to
        # `namespaceDefault` rather than `default` — see _helpers.tpl.
        "namespace": "",
        "namespaceDefault": "mini-baas",
        # deny-by-default NetworkPolicy (Checkov CKV2_K8S_6). ON by default to
        # mirror the hardened ../grobase chart. This is parity-safe: it changes
        # no workload (no image/env/port), allows ALL intra-release pod-to-pod
        # traffic + DNS, and only closes EXTERNAL ingress — and only on a CNI
        # that enforces NetworkPolicy (it is inert otherwise). Set
        # enabled=false to opt out.
        "networkPolicy": {
            "enabled": True,
            "ingressControllerNamespace": "ingress-nginx",
            # Components reachable from the ingress controller (the front door).
            "ingressTargets": ["kong", "waf"],
        },
        "edition": "lean",
        "services": base,
    })

    # 3) per-edition overlays — only flip enabled flags + record the edition
    for e, names in ed_services.items():
        overlay = {"edition": e, "services": {n: {"enabled": True} for n in names}}
        dump(os.path.join(HELM, f"values-{e}.yaml"), overlay)

    # 4) Kustomize overlays — manifest-driven component selection (per-service
    #    base manifests are produced from the Helm chart; the overlay records
    #    which services this edition includes for `kustomize`/GitOps consumers).
    for e, names in ed_services.items():
        dump(os.path.join(KUSTOMIZE, "overlays", e, "edition.yaml"), {
            "edition": e,
            "profiles": ed_profiles[e],
            "services": names,
        })

    print(f"deploy-gen: {len(services)} services, {len(editions)} editions, {len(core)} core")
    for e in sorted(editions):
        print(f"  edition {e:9s} -> {len(ed_services[e]):2d} services "
              f"({len(ed_profiles[e])} profiles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
